#
# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#

linters:
  enable:
    - govet
    - ineffassign
    - gofmt
    - revive
    - gosimple
    - gosec
    - errcheck
    - errname
    - goconst
    - staticcheck
    - typecheck
    - unused
  disable-all: true
  fast: true

issues:
  exclude:
    - stutter
