#
# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#

linters:
  enable:
    - govet
    - ineffassign
    - gofmt
    - golint
    - gosimple
    - deadcode
    - gosec
    - errcheck
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
  disable-all: true
  fast: true

issues:
  exclude:
    - stutter

run:
  skip-files:
    - fork_darwin.go
    - fork_linux.go
    - fork_windows.go
