///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Setting Cache Attributes

== Setting Cache Attributes

This example shows you how to set various attributes for a cache at runtime.  Only the *settable* attributes
such as the following can be modified: expiryDelay, highUnits, lowUnits, batchFactor, refreshFactor and requeueThreshold.

See the {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html#GUID-A443DF50-F151-4E9B-AFC9-DFEDF4B149E7[Cache MBean Reference]
for more information on the above attributes.

In the example below, we will set the `expiryDelay` for a cache.

NOTE: If you restart a cache node after setting an attribute, it will be reset to whatever the value was in
the cache configuration.

=== 1. List the members and caches

In this example we have a cluster of 3 storage-enabled members and a cache called `test`. Our context has been set to
`local` for our local cluster.

[source,bash]
----
# Get the members
$ cohctl get members
Using cluster connection 'local' from current context.

Total cluster members: 3
Cluster Heap - Total: 1.500GB, Used: 394MB, Available: 1.115GB (74.3%)

NODE ID  ADDRESS                      PORT  PROCESS  MEMBER  ROLE                  MAX HEAP  USED HEAP  AVAIL HEAP
      1  hostname-mac/192.168.1.124  60172    77425  n/a     Management               512MB       44MB       468MB
      2  hostname-mac/192.168.1.124  60178    77469  n/a     TangosolNetCoherence     512MB      190MB       322MB
      3  hostname-mac/192.168.1.124  60175    77447  n/a     TangosolNetCoherence     512MB      160MB       352MB

# Get the caches for the PartitionedCache service
$ cohctl get caches -s PartitionedCache
Using cluster connection 'local' from current context.

Total Caches: 1, Total primary storage: 0MB

SERVICE           CACHE  CACHE SIZE  BYTES   MB
PartitionedCache  test            0      0  0MB
----

=== 2. Use JsonPath to display the current expiryDelay

Use the following to retrieve the expiry delay and nodes for the cache test.

[source,bash]
----
$ cohctl get caches -o jsonpath="$.items[?(@.name == 'test')]..['name','expiryDelay','nodeId']" |jq
[
  "test",
  [
    0
  ],
  [
    "1",
    "2",
    "3"
  ]
]
----

NOTE: You will see only 1 value of `0` for expiry delay because this query returns the distinct values.

=== 3. Set the expiry delay for all nodes to 30 seconds

The default tier is `back` and can be changed using the `-t` option to `front` if required.

[source,bash]
----
$ cohctl set cache test -a expiryDelay -v 30 -s PartitionedCache
Using cluster connection 'local' from current context.

Selected service/cache: PartitionedCache/test
Are you sure you want to set the value of attribute expiryDelay to 30 in tier back for all 3 nodes? (y/n) y
operation completed
----

NOTE: You will now see a value of `30` for all nodes.

=== 4. Re-query the expiry delay

[source,bash]
----
$ cohctl get caches -o jsonpath="$.items[?(@.name == 'test')]..['name','expiryDelay','nodeId']" |jq
[
  "test",
  [
    30
  ],
  [
    "1",
    "2",
    "3"
  ]
]
----

=== 5. Set the expiry delay for node 1 to 120 seconds

[source,bash]
----
$ cohctl set cache test -a expiryDelay -v 120 -s PartitionedCache -n 1
Using cluster connection 'local' from current context.

Selected service/cache: PartitionedCache/test
Are you sure you want to set the value of attribute expiryDelay to 120 in tier back for 1 node(s)? (y/n) y
operation completed
----

=== 6. Re-query the expiry delay by describing the cache

[source,bash]
----
$ cohctl describe cache test -s PartitionedCache -o jsonpath="$.items[?(@.name == 'test')]..['expiryDelay','nodeId']" |jq
[
  30,
  "3",
  120,
  "1",
  30,
  "2"
]
----

=== See Also

* {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html#GUID-A443DF50-F151-4E9B-AFC9-DFEDF4B149E7[Cache MBean Reference]