///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Securing CLI Access

== Securing CLI Access

The Coherence CLI accesses cluster information using the Management over REST endpoint for the cluster as described in the
https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/rest-reference/quick-start.html[Coherence documentation].

Coherence HTTP Management server authentication and authorization are disabled by
default. We recommend that this is enabled as outlined in the sections below.

Another option for securing access to the management endpoint is to restrict HTTP access to the REST endpoint from trusted or management subnets
using standard networking firewall rules.

=== Enabling Basic Authentication

To enable basic authentication for Management over REST, please follow the instructions in the
https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/secure/securing-oracle-oracle-http-management-rest-server.html#GUID-816E45C4-2F52-4576-BC09-CF0B6E873CBA[basic authentication] section
of the Coherence documentation.

=== Enabling SSL Authentication

To enable SSL to provide authentication for Management over REST, please follow the instructions in the
https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/secure/securing-oracle-oracle-http-management-rest-server.html#GUID-7FC70A65-FC2F-4CBE-8F7D-7CBC3CDAA10A[SSL authentication]
section of the Coherence documentation.

=== Working with secured REST endpoints

If you have enabled basic authentication for your Management over REST endpoint, or you are connecting to a WebLogic Server cluster, you must
provide the `-U username` option on all `cohctl` commands.

To specify a password, you have the following options:

. Enter the password when prompted for, or
. Use the `-i` or `--stdin` option to read the password from standard in. (Useful for GitHub actions or automated processes)

[source,bash]
----
$ cohctl get members -U username
Enter password: *****
----

=== See Also

* https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/rest-reference/quick-start.html[REST API for Managing Oracle Coherence]
* https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/secure/securing-oracle-oracle-http-management-rest-server.html[Securing Oracle Coherence HTTP Management Over REST Server]