///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Troubleshooting Guide

== Troubleshooting Guide

The purpose of this page is to list troubleshooting guides and work-arounds for issues that you may run into when using the Coherence CLI.
This page will be updated and maintained over time to include common issues we see from customers.

== Contents

* <<bad, Bad CPU type in executable on OSX>>
* <<jfr, Null returned in JFR commands>>
* <<services, Cannot find services with quotes in their names>>

[#bad]
=== Bad CPU type in executable on OSX

If you received a message similar to the following then it is caused by installing the
incorrect OSX .pkg for your architecture.  E.g. you may have an AMD Mac and trying to install the
Apple Silicon version or visa-versa.

[source,command]
----
-bash: /usr/local/bin/cohctl: Bad CPU type in executable
----

Refer to the <<docs/installation/01_installation.adoc,Coherence CLI Installation section>> to uninstall
`cohctl` and download the correct pkg for your architecture.

You can run the `uname -a` command from a terminal and the output will indicate which type of architecture you have.

**AMD Processor**

[source,command]
----
$ uname -a
Darwin ... RELEASE_X86_64 x86_64
----

**Apple Silicon (M1)**

----
$ uname -a
Darwin ... RELEASE_ARM64_T8101 arm64
----

NOTE: Output above has been truncated for brevity.

[#jfr]
=== Null returned in JFR commands

If you see something similar to the following when running Java Flight Recorder (JFR) commands, where there is a null
instead of the member number, then this is a known issue.

You should apply the most recent available Coherence patch on version you are using to resolve this.

[source,bash]
----
$ cohctl get jfrs -c local

null->
   No available recordings.
   Use JFR.start to start a recording.
null->
   No available recordings.
   Use JFR.start to start a recording.
----

[#services]
=== Cannot find services with quotes in their names

Some Coherence services may have quotes in their names, especially if they contain a scope which is
delimited by a colon, as in WebLogic Server.
In these cases when you want to specify a service name you must enclose the whole service name in single quotes.

For example, take a look at the services for this WebLogic Server instance:

[source,bash]
----
$ cohctl get services -c wls -U weblogic
Enter password: ********

SERVICE NAME                      TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS
"ExampleGAR:PartitionedPofCache"  DistributedCache        4  NODE-SAFE        2         257
----

If we issue the following command you will see the error below.

[source,bash]
----
$ cohctl describe service "ExampleGAR:PartitionedPofCache" -c wls -U weblogic
Enter password: *******

Error: unable to find service with service name 'ExampleGAR:PartitionedPofCache'
----

You must surround the service name with single quotes.

[source,bash]
----
cohctl describe service '"ExampleGAR:PartitionedPofCache"' -c wls -U weblogic
Enter password: ******

SERVICE DETAILS
---------------
Name                                :  "ExampleGAR:PartitionedPofCache"
Type                                :  [DistributedCache]
Backup Count                        :  [1]
Backup Count After Writebehind      :  [1]
....
----

