///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Troubleshooting Guide
:description: Coherence CLI - Troubleshooting Guide
:keywords: oracle coherence, coherence-cli, documentation, management, cli, Troubleshooting Guide

== Troubleshooting Guide

The purpose of this page is to list troubleshooting guides and work-arounds for issues that you may run into when using the Coherence CLI.
This page will be updated and maintained over time to include common issues we see from customers.

== Contents

* <<bad, Bad CPU type in executable on macOS>>
* <<execute, Cannot execute [Exec format error] on Linux>>
* <<jfr, Null returned in JFR commands>>
* <<services, Cannot find services with quotes in their names>>
* <<wls, Issues adding correct cluster when WebLogic Server has multiple Coherence clusters>>
* <<windows, Issues setting reporter path on Windows>>
* <<create, Issues creating or starting clusters using `cohctl create cluster`>>
* <<completion, Issues using command completion with services, caches or topics with $ in the name>>
* <<bash, Issues with command completion on Mac using bash>>

[#bad]
=== Bad CPU type in executable on macOS

==== Problem

You receive a message similar to the following when trying to run the CLI on macOS:

[source,command]
----
/usr/local/bin/cohctl: Bad CPU type in executable
----

==== Solution

This is most likely caused by installing the incorrect macOS .pkg for your architecture.  E.g. you may have an AMD Mac and trying to install the
Apple Silicon version or visa-versa.

Refer to the xref:../installation/installation.adoc[Coherence CLI Installation section] to uninstall
`cohctl` and download the correct pkg for your architecture.

You can run the `uname -a` command from a terminal and the output will indicate which type of architecture you have. The last value on the line it will be either `x86_64` for AMD or `arm64` for M1.

**AMD Processor**

[source,command]
----
$ uname -a
Darwin ... RELEASE_X86_64 x86_64
----

**Apple Silicon (M1) Processor**

[source,command]
----
$ uname -a
Darwin ... RELEASE_ARM64_T8101 arm64
----

NOTE: Output above has been truncated for brevity.

[#execute]
=== Cannot execute [Exec format error] on Linux

==== Problem

You receive a message similar to the following when trying to run the CLI on Linux:

[source,command]
----
cohctl: cannot execute [Exec format error]
----

==== Solution

This is most likely caused by installing the incorrect linux executable for your architecture.  E.g. you may have an AMD Linux machine and trying to use
the ARM version or visa-versa.

Refer to the xref:../installation/installation.adoc[Coherence CLI Installation section] to uninstall
`cohctl` and download the correct binary for your architecture.

[#jfr]
=== Null returned in JFR commands

==== Problem

You see something similar to the following when running Java Flight Recorder (JFR) commands, where there is a null
instead of the member number.

[source,bash]
----
cohctl get jfrs -c local
----
Output:
[source,bash]
----
null->
   No available recordings.
   Use JFR.start to start a recording.
null->
   No available recordings.
   Use JFR.start to start a recording.
----

==== Solution

Then this is a known issue. To resolve you should apply the most recent available
Coherence patch on version you are using to resolve this.

[#services]
=== Cannot find services with quotes in their names

==== Problem

You are unable to describe or query services with quotes in their names.

Some Coherence services may have quotes in their names, especially if they contain a scope which is
delimited by a colon, as in WebLogic Server.
In these cases when you want to specify a service name you must enclose the whole service name in single quotes.

For example, take a look at the services for this WebLogic Server instance:

[source,bash]
----
cohctl get services -c wls -U weblogic
----
Output:
[source,bash]
----
Enter password: ********

SERVICE NAME                      TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS
"ExampleGAR:PartitionedPofCache"  DistributedCache        4  NODE-SAFE        2         257
----

If we issue the following command you will see the error below.

[source,bash]
----
cohctl describe service "ExampleGAR:PartitionedPofCache" -c wls -U weblogic
----
Output:
[source,bash]
----
Enter password: *******

Error: unable to find service with service name 'ExampleGAR:PartitionedPofCache'
----

==== Solution

You must surround any service names that have double quotes with single quotes.

[source,bash]
----
cohctl describe service '"ExampleGAR:PartitionedPofCache"' -c wls -U weblogic
----
Output:
[source,bash]
----
Enter password: ******

SERVICE DETAILS
---------------
Name                                :  "ExampleGAR:PartitionedPofCache"
Type                                :  [DistributedCache]
Backup Count                        :  [1]
Backup Count After Writebehind      :  [1]
....
----

[#wls]
=== Issues adding correct cluster when WebLogic Server has multiple Coherence clusters

==== Problem

When adding a connection to a WebLogic Server environment with multiple Coherence clusters,
present, by default only the first cluster will be added.

In the example below we have a WebLogic Server environment with two Coherence clusters: CoherenceCluster and CoherenceCluster2.

[source,bash]
----
cohctl add cluster wls1 -U weblogic -u http://host:7001/management/coherence/latest/clusters
----
Output:
[source,bash]
----
Enter password: *****
Added cluster wls1 with type http and URL http://host:7001/management/coherence/latest/clusters
----
Display the clusters.
[source,bash]
----
cohctl get clusters
----
Output:
[source,bash]
----
CONNECTION  TYPE  URL                                                     VERSION      CLUSTER NAME       TYPE       CTX
wls1        http  http://host:7001/management/coherence/latest/clusters   14.1.1.0.0   CoherenceCluster   WebLogic
----

==== Solution

You must supply the cluster name on the URL to add a specific cluster, rather than adding the default one found.

[source,bash]
----
cohctl add cluster wls2 -U weblogic -u http://host:7001/management/coherence/latest/clusters/CoherenceCluster2
----
Output:
[source,bash]
----
Enter password: ******
Added cluster wls2 with type http and URL http://host:7001/management/coherence/latest/clusters/CoherenceCluster2
----

Display the clusters.

[source,bash]
----
cohctl get clusters
----
Output:
[source,bash]
----
CONNECTION  TYPE  URL                                                                            VERSION      CLUSTER NAME        TYPE        CTX
wls1        http  http://host:7001/management/coherence/latest/clusters                    14.1.1.0.0   CoherenceCluster    WebLogic
wls2        http  http://host:7001/management/coherence/latest/clusters/CoherenceCluster2  14.1.1.0.0   CoherenceCluster2   WebLogic
----

[#windows]
=== Issues setting reporter path on Windows

==== Problem

When trying to set the reporter output path when your server is running on Windows, you
receive an error `response=500 Internal Server Error`.

For example:

[source,bash]
----
cohctl -y set reporter 1 -a outputPath -v D:\Temp\my_path
----
Output:
[source,bash]
----
cannot set value D:\Temp\my_path for attribute outputPath : response=500 Internal Server Error,
url=http://host:port/management/coherence/cluster/reporters/1
----

NOTE: On inspecting the server log you may see a message similar to `Unrecognized character escape`.

==== Solution

You must escape any backslash (`\`) in the path with an additional backslash:

[source,bash]
----
cohctl -y set reporter 1 -a outputPath -v D:\\Temp\\my_path
----
Output:
[source,bash]
----
operation completed
----

[#create]
=== Issues creating or starting clusters

If you have used the `cohctl create cluster` or `cohctl start cluster` and you cannot
show the cluster information using a command such as `cohctl get members`, then you can do
the following to check if there are any issues.

NOTE: The main reasons for clusters not starting up are that you have not used the correct JDK version.
For example for 22.09 and above clusters you must have JDK 17+.

==== Solution

===== Check the logfile for the cluster

The logfiles for a created cluster are in the following location `$HOME/.cohctl/logs/<cluster>` and
you should check these if you cluster is not starting up.

[source,bash]
----
cat ~/.cohctl/logs/local/storage-0.log
----

If you see the following message, this indicates that you are not using a compatible JDK for the Coherence version.

[source,bash]
----
Error: LinkageError occurred while loading main class com.tangosol.net.Coherence
java.lang.UnsupportedClassVersionError: com/tangosol/net/Coherence has been compiled by a more recent version of the Java Runtime
   (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
----

[#completion]
=== Issues using command completion with services, caches or topics with $ in the name

If you use command completion, and you try to describe services, caches or topics with `$` in the name then the
command completion may not work correctly.

For example, using `cohctl get services` you see:

[source,bash]
----
cohctl get services
----
Output:
[source,bash]
----
Using cluster connection 'main' from current context.

SERVICE NAME            TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS
"$SYS:Config"           DistributedCache        3  NODE-SAFE        3         257
"$SYS:HealthHttpProxy"  Proxy                   3  n/a             -1          -1
"$SYS:SystemProxy"      Proxy                   3  n/a             -1          -1
ManagementHttpProxy     Proxy                   1  n/a             -1          -1
PartitionedCache        DistributedCache        3  NODE-SAFE        3         257
PartitionedTopic        PagedTopic              3  NODE-SAFE        3         257
Proxy                   Proxy                   3  n/a             -1          -1
----

If you try to use `cohctl describe service` then press `TAB` twice, you will see:

[source,bash]
----
cohctl describe service
----
Output:
[source,bash]
----
"$SYS:Config"           "$SYS:HealthHttpProxy"  "$SYS:SystemProxy"      ManagementHttpProxy     PartitionedCache        PartitionedTopic        Proxy
----

You cannot complete any services using command completion with `$` in their name using `TAB` twice.

==== Solution

For any services that have $ such as `"$SYS:Config"` you need to copy/paste the service name to describe
and enclose the name in single quote. For example:

[source,bash]
----
cohctl describe service '"$SYS:Config"'
----


[#bash]
=== Issues with command completion on Mac using bash

==== Problem

When you are using `bash` and have setup command completion using instructions xref:../config/command_completion.adoc[here],
and you receive this error:

[source,bash]
----
bash: _get_comp_words_by_ref: command not found
----

==== Solution

You should first install `bash-completion` using `brew`. See https://formulae.brew.sh/formula/bash-completion[https://formulae.brew.sh/formula/bash-completion].

Then add the following to your `.bash_profile` which should resolve the issue:


[source,bash]
----
[[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
----
