///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Coherence CLI Introduction

== What is the Coherence CLI?

The Coherence command line interface, `cohctl`, is a lightweight tool, in the tradition of tools such as kubectl,
which can be scripted or used interactively to manage and monitor Coherence clusters. You can use `cohctl` to view cluster information
such as services, caches, members, etc, as well as perform various management operations against clusters.

The CLI accesses clusters using the HTTP Management over REST interface and therefore requires this to be enabled on any clusters
you want to monitor or manage. See the {commercial-docs-base-url}/rest-reference/quick-start.html[Coherence Documentation]
for more information on setting up Management over REST.

The CLI is certified with the latest Coherence Community Edition (CE) versions as well as Coherence Commercial versions 12.2.1.4, 14.1.1.0.x, 14.1.1.2206.x and above.

To view the release notes for the latest version of the CLI ({cli-version}), see https://github.com/oracle/coherence-cli/releases[GitHub].

NOTE: The CLI does not replace current management and monitoring tools such as the https://github.com/oracle/coherence-visualvm[Coherence VisualVM Plugin],
https://docs.oracle.com/cd/E24628_01/install.121/e24215/coherence_getstarted.htm#GSSOA10121[Enterprise Manager], or https://oracle.github.io/coherence-operator/docs/latest/#/docs/metrics/040_dashboards[Grafana Dashboards], but complements and
provides a lightweight and scriptable alternative.

== Why use the Coherence CLI?

The CLI complements your existing Coherence management tools and allows you to:

. Interactively monitor your Coherence clusters from a lightweight terminal-based interface
. Monitor service "StatusHA" during rolling restarts of Coherence clusters
. Script Coherence monitoring and incorporate results into other management tooling
. Output results in various formats including text, JSON and utilize JsonPath to extract attributes of interest
. Gather information that may be useful for Oracle Support to help diagnose issues
. Connect to standalone or WebLogic Server based clusters from commercial versions 12.2.1.4 and above as well as all https://github.com/oracle/coherence[Coherence Community Edition] (CE) versions
. Retrieve thread dumps and Java Flight Recordings across members
. Make changes to various modifiable JMX attributes on services, caches and members

NOTE: There are *experimental* features in this release which allow you to create/ start/ stop/ scale Coherence clusters for development
purposes only. See <<docs/reference/98_create_clusters.adoc,Creating Clusters documentation>> for more information.

== Next Steps

* <<docs/installation/01_installation.adoc,Install the Coherence CLI>>
* <<docs/about/03_quickstart.adoc,Run the Quick Start>>
* <<docs/reference/01_overview.adoc,Explore the Command Reference>>
