///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Quick Start

== Overview

This guide is a simple set of steps to get you started with the Coherence CLI.

== Prerequisites

1. You must have downloaded and installed the CLI for your platform as described in the
<<docs/installation/01_installation.adoc,Coherence CLI Installation section>>.

2. You must have a Coherence cluster running that has Management over REST configured.
+
NOTE: See the https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/rest-reference/quick-start.html[Coherence Documentation]
for more information on setting up Management over REST.
+
If you do not have a cluster running with Management over REST, you can run the following Docker
image to start a Coherence CE cluster and expose management on port 30000.
+
[source,bash,subs="attributes"]]
----
docker run -d -p 30000:30000 ghcr.io/oracle/coherence-ce:{coherence-version}
----

== Contents

. <<step1, Display the Coherence CLI version>>
. <<step2, Display CLI usage>>
. <<step3, Add a cluster connection>>
. <<step4, Describe the cluster>>
. <<step5, Display services>>
. <<step6, Describe a service>>
. <<step7, Watching data>>
. <<step8, Change the output format to Json and using JsonPath>>

[#step1]
=== 1. Display the Coherence CLI version

Issue the following command to show the version details of the tool you are using.

[source,bash,subs="attributes"]
----
$ cohctl version

Coherence Command Line Interface
CLI Version: {cli-version}
Date:        2021-10-13T02:36:48Z
Commit:      6d1266bb473dad224a3672367126381263af
OS:          darwin
OS Version:  amd64
----

NOTE: THE CLI creates a hidden directory off the users home directory called `.cohctl` to store the cluster connection information plus other
information. You can issue `ls -l ~/.cohctl` on Mac/Linux to view the directory contents.

[#step2]
=== 2. Display CLI usage

If you run `cohctl` without any arguments you will see the usage.
These options are explained in detail in  <<docs/config/05_global_flags.adoc,Global Flags>>.

[source,bash]
----
$ cohctl --help

include::../../build/_output/docs-gen/cohctl_help.adoc[tag=text]
----

[#step3]
=== 3. Add a cluster connection

Next, you must add a connection to a Coherence cluster.  In this example the cluster is running on
the local machine and the Management over REST port is 30000. Adjust for your Coherence cluster.

When you add a cluster connection you give it a context name, which may be different that the cluster name and url to
connect to.

[source,bash]
----
$ cohctl add cluster local -u http://localhost:30000/management/coherence/cluster
Added cluster local with type http and URL http://localhost:30000/management/coherence/cluster

$ cohctl get clusters
CONNECTION  TYPE  URL                                                  VERSION  CLUSTER NAME  CLUSTER TYPE  CTX
local       http  http://localhost:30000/management/coherence/cluster  21.12    my-cluster    Standalone
----

NOTE: If you are not using a Docker container, you can also use the `cohctl discover clusters` command to automatically discover clusters using the Name Service.

[#step4]
=== 4. Describe the cluster

Now that the cluster connection is added, you can describe the cluster using the `describe cluster` command.

[source,bash]
----
$ cohctl describe cluster local
CLUSTER
-------
Cluster Name:    my-cluster
Version:         21.12
Cluster Size:    3
License Mode:    Development
Departure Count: 0
Running:         true

MEMBERS
-------
Cluster Heap - Total: 1.750GB, Used: 156MB, Available: 1.598GB (91.3%)

NODE ID  ADDRESS          PORT  PROCESS  MEMBER  ROLE              MACHINE  RACK  SITE  PUBLISHER  RECEIVER  MAX HEAP  USED HEAP  AVAIL HEAP
1        /192.168.1.121  57133  13919    n/a     Management        n/a      n/a   n/a   0.994      1.000     512MB     114MB      398MB
2        /192.168.1.121  57136  13941    n/a     CoherenceServer   n/a      n/a   n/a   1.000      1.000     1.000GB   23MB       1,001MB
3        /192.168.1.121  57169  13981    n/a     CoherenceConsole  n/a      n/a   n/a   1.000      1.000     256MB     19MB       237MB

SERVICES
-------
SERVICE NAME         TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS  ENDANGERED  VULNERABLE  UNBALANCED  STATUS
Proxy                Proxy             2        n/a        -1       -1          -1          -1          -1          n/a
PartitionedTopic     DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
PartitionedCache2    DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
PartitionedCache     DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
ManagementHttpProxy  Proxy             2        n/a        -1       -1          -1          -1          -1          n/a

CACHES
-------
Total Caches: 2, Total primary storage: 30MB

SERVICE           CACHE  CACHE SIZE  BYTES       MB    AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache  test1  100,000     26,288,448  25MB  262       200,000     0           0              0           0             0.00%
PartitionedCache  test2  23,000      5,999,040   5MB   260       46,000      0           0              0           0             0.00%

PROXY SERVERS
-------------
NODE ID  HOST IP              SERVICE NAME  CONNECTIONS  BYTES SENT  BYTES REC  MSG SENT  MSG RCV  BYTES BACKLOG  MSG BACKLOG  UNAUTH
1        0.0.0.0:57133.50631  Proxy         0            0           0          0         1        0              0            0
2        0.0.0.0:57136.59773  Proxy         0            0           0          0         1        0              0            0

HTTP SERVERS
-------------
NODE ID  HOST IP        SERVICE NAME         SERVER TYPE                                    REQUESTS  ERRORS  RESP 1xx  RESP 2xx  RESP 3xx  RESP 4xx  RESP 5xx
1        0.0.0.0:30000  ManagementHttpProxy  com.tangosol.coherence.http.DefaultHttpServer  12        0       0         8         0         3         0
2        0.0.0.0:0      ManagementHttpProxy  com.tangosol.coherence.http.DefaultHttpServer  0         0       0         0         0         0         0
----

NOTE: Depending upon the services and caches running in your cluster, you will see something slightly different.

[#step5]
=== 5. Display services

You can issue various `get` commands to display different resources. Issue the `get services` command to
show the services for the cluster only.

[source,bash]
----
$ cohctl get services -c local

SERVICE NAME         TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS  ENDANGERED  VULNERABLE  UNBALANCED  STATUS
Proxy                Proxy             2        n/a        -1       -1          -1          -1          -1          n/a
PartitionedTopic     DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
PartitionedCache2    DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
PartitionedCache     DistributedCache  3        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
ManagementHttpProxy  Proxy             2        n/a        -1       -1          -1          -1          -1          n/a
----

All commands other than `describe cluster` require a `-c` option to specify the cluster you wish to
connect to. You can use the `cohctl set context <name>` to specify the context (or cluster
connection) you are working  with, so you don't have to specify `-c` each time.

[source,bash]
----
$ cohctl set context local
Current context is now local

$ cohctl get services
SERVICE NAME         TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS  ENDANGERED  VULNERABLE  UNBALANCED  STATUS
Proxy                Proxy             2        n/a        -1       -1          -1          -1          -1          n/a
PartitionedTopic     DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
PartitionedCache2    DistributedCache  2        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
PartitionedCache     DistributedCache  3        NODE-SAFE  2        257         0           257         0           257 partitions are vulnerable
ManagementHttpProxy  Proxy             2        n/a        -1       -1          -1          -1          -1          n/a
----

[#step6]
=== 6. Describe a service

Above we have issued a `get services` command and for all resources you can use a `describe` command to
show specific details about a resource, or a service in our case.

The output from a `describe` command will usually contain much more detailed information about the resource.

[source,bash]
----
$ cohctl describe service PartitionedCache

Using cluster connection 'local' from current context.

SERVICE DETAILS
---------------
Name                                :  PartitionedCache
Type                                :  [DistributedCache]
Backup Count                        :  [1]
Backup Count After Writebehind      :  [1]
Event Backlog                       :  0
Event Count                         :  0
...

Thread Count Min                    :  [1]
Thread Count Update Time            :  [1970-01-01T00:00:00.000+00:00]
Thread Idle Count                   :  2
Thread Pool Sizing Enabled          :  map[true:3]
Transport Backlogged Connection List:  [[] [] []]

SERVICE MEMBERS
---------------
NODE ID  THREADS  IDLE  THREAD UTIL  MIN THREADS  MAX THREADS    TASK COUNT  TASK BACKLOG  PRIMARY OWNED  BACKUP OWNED  REQ AVG MS  TASK AVG MS
1        1        1     0.00%        1            2,147,483,647  1,230       0             129            128           7.0541      0.6220
2        1        1     0.00%        1            2,147,483,647  1,230       0             128            129           7.7920      0.6569
3        0        -1    n/a          1            2,147,483,647  -1          0             0              0             2.1454      -1.0000

SERVICE CACHES
--------------
Total Caches: 2, Total primary storage: 30MB

SERVICE           CACHE  CACHE SIZE  BYTES       MB    AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache  test1  100,000     26,288,448  25MB  262       200,000     0           0              0           0             0.00%
PartitionedCache  test2  23,000      5,999,040   5MB   260       46,000      0           0              0           0             0.00%

PERSISTENCE FOR SERVICE
-----------------------
Total Active Space Used: 0MB
NODE ID  PERSISTENCE MODE  ACTIVE BYTES USED  ACTIVE SPACE USED  AVG LATENCY  MAX LATENCY
1        on-demand         0                  0MB                0.000ms      0ms
2        on-demand         0                  0MB                0.000ms      0ms


PERSISTENCE COORDINATOR
-----------------------
Coordinator Id  :  1
Idle            :  true
Operation Status:  Idle
Snapshots       :  []
----

NOTE: The output above has been truncated for brevity.

[#step7]
=== 7. Watching data

For all the `get` commands, you can add the `-w` option to watch the resource continuously until `CTRL-C`
has been pressed.  In the example below we are watching the cluster members.

[source,bash]
----
$ cohctl get members -w
2021-10-13 15:09:52.027636 +0800 AWST m=+0.059034774
Using cluster connection 'local' from current context.

Cluster Heap - Total: 1.750GB, Used: 330MB, Available: 1.428GB (81.6%)

NODE ID  ADDRESS          PORT  PROCESS  MEMBER  ROLE              MAX HEAP  USED HEAP  AVAIL HEAP
1        /192.168.1.121  57133  13919    n/a     Management           512MB      186MB       326MB
2        /192.168.1.121  57136  13941    n/a     CoherenceServer    1.000GB       67MB       957MB
3        /192.168.1.121  57169  13981    n/a     CoherenceConsole     256MB       77MB       179MB

2021-10-13 15:09:57.045536 +0800 AWST m=+5.076898506
Using cluster connection 'local' from current context.

Cluster Heap - Total: 1.750GB, Used: 332MB, Available: 1.426GB (81.5%)

NODE ID  ADDRESS          PORT  PROCESS  MEMBER  ROLE              MAX HEAP  USED HEAP  AVAIL HEAP
1        /192.168.1.121  57133  13919    n/a     Management           512MB      186MB       326MB
2        /192.168.1.121  57136  13941    n/a     CoherenceServer    1.000GB       68MB       956MB
3        /192.168.1.121  57169  13981    n/a     CoherenceConsole     256MB       77MB       179MB
----

NOTE: You can change the delay from the default of 5 seconds by using `-d` option and specifying the seconds
to delay, e.g. `cohctl get members -w -d 10`.

NOTE: You can also use `-o wide` to display more columns on most commands.

[#step8]
=== 8. Change the output format to Json and using JSONPath

The default output format is text, but you can specify `-o json` on any command to get the output
in Json format. You can also use `-o jsonpath="..."` to apply a JsonPath expression.

Below we are changing the format for the `get members` to be Json and piping it thought the `jq` utility to format.

[source,bash]
----
$ cohctl get members -o json | jq

{
  "items": [
    {
      "processName": "13981",
      "socketCount": -1,
      "siteName": "n/a",
      "publisherSuccessRate": 1,
      "trafficJamCount": 8192,
      "multicastEnabled": true,
      "refreshTime": "2021-10-13T15:12:58.476+08:00",
...
}
----

We can also JSONPath expressions to select or
query json output from any command. In the example below we get all service members
where the requestAverageDuration > 15 millis.

[source,bash]
----
$ cohctl get services -o jsonpath="$.items[?(@.requestAverageDuration > 15)]..['nodeId','name','requestAverageDuration']"
[
  "2",
  "PartitionedCache2",
  25.51414,
  "1",
  "PartitionedCache2",
  19.662437
]
----

See the <<docs/examples/10_jsonpath.adoc,JSONPath>> examples for more information.

=== Next Steps

Explore more of the commands HERE.