///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Overview

== Reference

The Coherence CLI contains many commands to manage and monitor Coherence clusters.

[PILLARS]
====
[CARD]
.Clusters
[link=docs/reference/05_clusters.adoc]
--
Manage Cluster Connections.
--

[CARD]
.Contexts
[link=docs/reference/10_contexts.adoc]
--
Adding arbitrary JVM arguments and system properties.
--

[CARD]
.Members
[link=docs/reference/15_members.adoc]
--
Display and describe member information.
--

[CARD]
.Machines
[link=docs/reference/17_machines.adoc]
--
Display and describe machine information.
--

[CARD]
.Services
[link=docs/reference/20_services.adoc]
--
Display and describe service information.
--

[CARD]
.Caches
[link=docs/reference/25_caches.adoc]
--
Display and describe cache information.
--

[CARD]
.Topics
[link=docs/reference/30_topics.adoc]
--
Display Topics information.
--

[CARD]
.Persistence
[link=docs/reference/40_persistence.adoc]
--
Display and perform Persistence operations.
--

[CARD]
.Federation
[link=docs/reference/42_federation.adoc]
--
Display and perform Federation operations.
--

[CARD]
.Proxy Servers
[link=docs/reference/50_proxies.adoc]
--
Display and describe proxy server information.
--

[CARD]
.Http Proxy Servers
[link=docs/reference/55_http_servers.adoc]
--
Display and describe Http proxy server information.
--

[CARD]
.Elastic Data
[link=docs/reference/56_elastic_data.adoc]
--
Display and describe Elastic Data information.
--

[CARD]
.Http Sessions
[link=docs/reference/58_http_sessions.adoc]
--
Display and describe Coherence*Web Http session information.
--

[CARD]
.Executors
[link=docs/reference/60_executors.adoc]
--
Display and describe Executors.
--

[CARD]
.Reporters
[link=docs/reference/66_reporters.adoc]
--
Display and manage Coherence reporters.
--

[CARD]
.Diagnostics
[link=docs/reference/85_diagnostics.adoc]
--
Take multiple thread dumps, heap dumps or JFR's across members.
--

[CARD]
.NS Lookup
[link=docs/reference/45_nslookup.adoc]
--
Look up various Name Service endpoints for a cluster.
--

[CARD]
.Miscellaneous
[link=docs/reference/95_misc.adoc]
--
Various settings related commands.
--

====
