///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2023 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Members

== Members

=== Overview
There are various cluster commands that allow you to work with and manage cluster members.

* <<get-members, `cohctl get members`>> - displays the members for a cluster
* <<get-member-stats, `cohctl get member-stats`>> - displays the member network statistics for a cluster
* <<describe-member, `cohctl describe member`>> - shows information related to a specific member
* <<set-member, `cohctl set member`>> - sets a member attribute for one or more members
* <<shutdown-member, `cohctl shutdown member`>> - shuts down a members services in a controlled manner

[#get-members]
==== Get Members

include::../../build/_output/docs-gen/get_members.adoc[tag=text]

*Examples*

Display all members and specify to display memory sizes in MB using `-m` option.

[source,bash]
----
$ cohctl get members -c local -m

Total cluster members: 3
Cluster Heap - Total: 4,352 MB Used: 250 MB Available: 4,102 MB (94.3%)
Storage Heap - Total: 4,096 MB Used: 201 MB Available: 3,895 MB (95.1%)

NODE ID  ADDRESS         PORT   PROCESS  MEMBER  ROLE                  STORAGE  MAX HEAP  USED HEAP  AVAIL HEAP
      1  192.168.1.117  63984    35372  n/a     Management            true     2,048 MB      91 MB    1,957 MB
      2  192.168.1.117  63995    35398  n/a     TangosolNetCoherence  true     2,048 MB     110 MB    1,938 MB
      3  192.168.1.117  64013    35430  n/a     CoherenceConsole      false      256 MB      49 MB      207 MB
----

NOTE: The default memory display format is bytes but can be changed by using `-k`, `-m` or `-g`.

Display all members with the role `CoherenceConsole`.

[source,bash]
----
$ cohctl get members -c local -r CoherenceConsole -m

Total cluster members: 1
Cluster Heap - Total: 256 MB Used: 50 MB Available: 206 MB (80.5%)
Storage Heap - Total: 0 MB Used: 0 MB Available: 0 MB ( 0.0%)

NODE ID  ADDRESS         PORT   PROCESS  MEMBER  ROLE              STORAGE  MAX HEAP  USED HEAP  AVAIL HEAP
      3  192.168.1.117  64013    35430  n/a      CoherenceConsole  false      256 MB      50 MB      206 MB
----

NOTE: You can also use `-o wide` to display more columns.

[#get-member-stats]
==== Get Member Stats

include::../../build/_output/docs-gen/get_member_stats.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl get member-stats -c local

Total cluster members: 3
NODE ID  ADDRESS     PORT   PROCESS  MEMBER                         ROLE              PKT SENT  PKT REC  RESENT  EFFICIENCY  SEND Q  DATA SENT  DATA REC  WEAKEST
      1  /127.0.0.1  50724    81363  storage-1                      CoherenceServer        531      586       2     100.00%       0       8 MB      9 MB        4
      2  /127.0.0.1  50725    81364  storage-2                      CoherenceServer        181      152       0     100.00%       0       8 MB      8 MB       -1
      3  /127.0.0.1  50726    81362  storage-0                      CoherenceServer        182      148       0     100.00%       0       7 MB     10 MB       -1
      4  /127.0.0.1  50968    81733  com.tangosol.net.CacheFactory  CoherenceConsole        64       58       0     100.00%       0       3 MB      0 MB       -1
----

[#describe-member]
==== Describe Member

include::../../build/_output/docs-gen/describe_member.adoc[tag=text]

*Examples*

Describe member and include heap dump.

[source,bash]
----
$ cohctl describe member 1 -D
----

NOTE: When taking one or more thread dumps, if you want full deadlock analysis, you should set the following system property
on your Coherence JVMS `-Dcom.oracle.coherence.common.util.Threads.dumpLocks=FULL`

Describe member and include extended information on G1 garbage collection.

[source,bash]
----
$ cohctl describe member 1 -Xg1
----

[#set-member]
==== Set Member

include::../../build/_output/docs-gen/set_member.adoc[tag=text]

*Examples*

Set the log level for all members.

[source,bash]
----
# Check the log level first
$ cohctl get members -o json | jq | grep loggingLevel
      "loggingLevel": 6,
      "loggingLevel": 6,
      "loggingLevel": 6,

$ cohctl set member all -a loggingLevel -v 6 -c local

re you sure you want to set the value of attribute loggingLevel to 6 for all 3 nodes? (y/n) y
operation completed
$ cohctl get members -o json | jq | grep loggingLevel
      "loggingLevel": 6,
      "loggingLevel": 6,
      "loggingLevel": 6,
----

Set the log level to 9 for node id 1.

[source,bash]
----
$ cohctl set member 1 -a loggingLevel -v 9 -c local

Are you sure you want to set the value of attribute loggingLevel to 9 for 1 nodes? (y/n) y
operation completed

$ cohctl get members -o json | jq | grep loggingLevel
      "loggingLevel": 9,
      "loggingLevel": 6,
      "loggingLevel": 6,
----

[#shutdown-member]
==== Shutdown Member

include::../../build/_output/docs-gen/shutdown_member.adoc[tag=text]

[source,bash]
----
$ cohctl shutdown member 1 -c local
Are you sure you want to shutdown member 1? (y/n) y
operation completed
----

NOTE: This command may take a while to complete. Check the server logs for information regarding the
member's status.  If the services were started using DefaultCacheServer, then they will be restarted.

=== See Also

* <<docs/reference/85_diagnostics.adoc,Diagnostics>>



