///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Caches

== Caches

=== Overview
There are various commands that allow you to work with and manage cluster caches.

* <<get-caches, `cohctl get caches`>> - displays the caches for a cluster
* <<describe-cache, `cohctl describe cache`>> - shows information related to a specific cache and service
* <<set-cache, `cohctl set cache`>> - sets an attribute for a cache across one or more members

[#get-caches]
==== Get Caches

include::../../build/_output/docs-gen/get_caches.adoc[tag=text]

*Examples*

Display all caches.

[source,bash]
----
$ cohctl get caches -c local -o wide
Total Caches: 3, Total primary storage: 16MB

SERVICE            CACHE     CACHE SIZE       BYTES    MB  AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache   test1        100,000  16,800,000  16MB       168     200,000           0              0           0             0     0.00%
PartitionedCache   test2            123     142,680   0MB     1,160         246           0              0           0             0     0.00%
PartitionedCache2  test-123           0           0   0MB         0           0           0              0           0             0     0.00%
----

NOTE: If you do not use the `-o wide` option, then you will only see service, cache name, cache size and bytes.

Display all caches for a particular service.

[source,bash]
----
$ cohctl get caches -c local -s PartitionedCache2 -o wide

Total Caches: 1, Total primary storage: 0MB

SERVICE            CACHE     CACHE SIZE  BYTES   MB  AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache2  test-123           0      0  0MB         0           0           0              0           0             0     0.00%
----

[#describe-cache]
==== Describe Cache

include::../../build/_output/docs-gen/describe_cache.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl describe cache test -c local -s PartitionedCache

CACHE DETAILS
-------------
Service         :  PartitionedCache
Name            :  test
Type            :  Cache
Description     :  Implementation: com.tangosol.net.cache.LocalCache
Cache Store Type:  NONE

CACHE SIZE AND ACCESS DETAILS
-----------------------------
NODE ID  TIER     SIZE  MEMORY BYTES  MEMORY MB  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES
      1  back   50,221    13,202,128       12MB      50,221      50,221              0
      3  back   49,779    13,086,320       12MB      49,779      49,779              0
      4  front       0             0        0MB     100,000           0              0

CACHE STORAGE DETAILS
---------------------
NODE ID  TIER   LOCKS GRANTED  LOCKS PENDING  LISTENERS  MAX QUERY MS  MAX QUERY DESC
      1  back               0              0          0             0
      3  back               0              0          0             0
      4  front              0              0          0             0

INDEX DETAILS
-------------
Total Indexing Bytes:  15,999,992
Total Indexing:        15MB
Total Indexing Millis: 800

Node:1:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=7.66MB, Content=50220
Node:3:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=7.59MB, Content=49778
----

NOTE: You can also use the `-o wide` option to display more detailed information.

[source,bash]
----
$ cohctl describe cache test -c local -s PartitionedCache -o wide

CACHE DETAILS
-------------
Service         :  PartitionedCache
Name            :  test
Type            :  Cache
Description     :  Implementation: com.tangosol.net.cache.LocalCache
Cache Store Type:  NONE

CACHE SIZE AND ACCESS DETAILS
-----------------------------
NODE ID  TIER     SIZE  MEMORY BYTES  MEMORY MB  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES    HITS  MISSES  HIT PROB  STORE READS  WRITES  FAILURES
      1  back   50,221    13,202,128       12MB      50,221      50,221              0  50,221       0   100.00%           -1      -1        -1
      3  back   49,779    13,086,320       12MB      49,779      49,779              0  49,779       0   100.00%           -1      -1        -1
      4  front       0             0        0MB     100,000           0              0       0       0     0.00%           -1      -1        -1

CACHE STORAGE DETAILS
---------------------
NODE ID  TIER   LOCKS GRANTED  LOCKS PENDING  LISTENERS  MAX QUERY MS  MAX QUERY DESC  NO OPT AVG  OPT AVG  INDEX BYTES  INDEX MB  INDEXING MILLIS
      1  back               0              0          0             0                      0.0000   0.0000    8,035,352       7MB              411
      3  back               0              0          0             0                      0.0000   0.0000    7,964,640       7MB              389
      4  front              0              0          0             0                      0.0000   0.0000            0       0MB                0

INDEX DETAILS
-------------
Total Indexing Bytes:  15,999,992
Total Indexing:        15MB
Total Indexing Millis: 800

Node:1:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=7.66MB, Content=50220
Node:3:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=7.59MB, Content=49778
----

[#set-cache]
==== Set Cache

include::../../build/_output/docs-gen/set_cache.adoc[tag=text]

See the https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/manage/oracle-coherence-mbeans-reference.html[Cache MBean Reference]
for more information on the above attributes.

*Examples*

Set the expiry delay for all nodes to 30 seconds. (we are assuming we have 3 storage-enabled nodes)

[source,bash]
----
$ cohctl set cache test -a expiryDelay -v 30 -s PartitionedCache
Using cluster connection 'local' from current context.

Selected service/cache: PartitionedCache/test
Are you sure you want to set the value of attribute expiryDelay to 30 in tier back for all 3 nodes? (y/n) y
operation completed
----

NOTE: See <<docs/examples/15_set_cache_attrs.adoc,here>> for a more detailed example of this command.


=== See Also

* <<docs/reference/20_services.adoc,Services>>
* <<docs/reference/30_topics.adoc,Topics>>


