///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Caches

== Caches

=== Overview
There are various commands that allow you to work with and manage cluster caches.

* <<get-caches, `cohctl get caches`>> - displays the caches for a cluster
* <<describe-cache, `cohctl describe cache`>> - shows information related to a specific cache and service
* <<get-cache-stores, `cohctl get cache-stores`>> - displays the cache stores for a cache and service
* <<set-cache, `cohctl set cache`>> - sets an attribute for a cache across one or more members

[#get-caches]
==== Get Caches

include::../../build/_output/docs-gen/get_caches.adoc[tag=text]

*Examples*

Display all caches and display cache size in MB using `-m` option.

[source,bash]
----
$ cohctl get caches -c local -o wide -m
Total Caches: 2, Total primary storage: 36 MB

SERVICE           CACHE        COUNT   SIZE  AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache  customers  100,000  25 MB       262     200,000           0              0           0             0     0.00%
PartitionedCache  orders      10,000  11 MB     1,160      20,000      20,000              0      20,000             0   100.00%
----

NOTE: If you do not use the `-o wide` option, then you will only see service, cache name, count and size.

Display all caches for a particular service.

[source,bash]
----
$ cohctl get caches -c local -s PartitionedCache -o wide -m

Total Caches: 2, Total primary storage: 36 MB

SERVICE           CACHE        COUNT   SIZE  AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache  customers  100,000  25 MB       262     200,000           0              0           0             0     0.00%
PartitionedCache  orders      10,000  11 MB     1,160      20,000      20,000              0      20,000             0   100.00%
----

[#describe-cache]
==== Describe Cache

include::../../build/_output/docs-gen/describe_cache.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl describe cache orders -c local -s PartitionedCache -m

CACHE DETAILS
-------------
Service         :  PartitionedCache
Name            :  orders
Type            :  Cache
Description     :  Implementation: com.tangosol.net.cache.LocalCache
Cache Store Type:  NONE

CACHE SIZE AND ACCESS DETAILS
-----------------------------
NODE ID  TIER   COUNT  SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES
      1  back   5,022  5 MB       5,022      10,044              0
      2  back   4,978  5 MB       4,978       9,956              0
      3  front      0  0 MB      10,000           0              0

CACHE STORAGE DETAILS
---------------------
NODE ID  TIER   LOCKS GRANTED  LOCKS PENDING  LISTENERS  MAX QUERY MS  MAX QUERY DESC
      1  back               0              0          0             0
      2  back               0              0          0             0
      3  front              0              0          0             0

INDEX DETAILS
-------------
Total Indexing Bytes:  2,720,664
Total Indexing:        2 MB
Total Indexing Millis: 263

Node:1:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=784KB, Content=5022
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=549KB, Content=5022
Node:2:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=777KB, Content=4978
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=544KB, Content=4978

CACHE STORE DETAILS
-------------------
Total Queue Size:     6,708,931
Total Store Failures: 0
Total Store Failures: 0

NODE ID  QUEUE SIZE  WRITES  AVG BATCH  AVG WRITE  TOTAL WRITE  FAILURES  READS  AVG READ  TOTAL READ
      1   2,261,151   8,042        127      266ms      35m 43s         0      0       0ms        0.0s
      2   2,222,822   7,966        127      266ms      35m 21s         0      0       0ms        0.0s
      3   2,224,958   7,937        127      266ms      35m 18s         0      0       0ms        0.0s
----

NOTE: You can also use the `-o wide` option to display more detailed information.

NOTE: The default memory display format is bytes but can be changed by using `-k`, `-m` or `-g`.

[source,bash]
----
$ cohctl describe cache test -c local -s PartitionedCache -o wide -m

CACHE DETAILS
-------------
Service         :  PartitionedCache
Name            :  orders
Type            :  Cache
Description     :  Implementation: com.tangosol.net.cache.LocalCache
Cache Store Type:  NONE

CACHE SIZE AND ACCESS DETAILS
-----------------------------
NODE ID  TIER   COUNT  SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES    HITS  MISSES  HIT PROB  STORE READS  WRITES  FAILURES
      1  back   5,022  5 MB       5,022      10,044              0  10,044       0   100.00%           -1      -1        -1
      2  back   4,978  5 MB       4,978       9,956              0   9,956       0   100.00%           -1      -1        -1
      3  front      0  0 MB      10,000           0              0       0       0     0.00%           -1      -1        -1

CACHE STORAGE DETAILS
---------------------
NODE ID  TIER   LOCKS GRANTED  LOCKS PENDING  LISTENERS  MAX QUERY MS  MAX QUERY DESC  NO OPT AVG  OPT AVG  INDEX SIZE  INDEXING MILLIS
      1  back               0              0          0             0                      0.0000   0.0000        1 MB              118
      2  back               0              0          0             0                      0.0000   0.0000        1 MB              145
      3  front              0              0          0             0                      0.0000   0.0000        0 MB                0

INDEX DETAILS
-------------
Total Indexing Bytes:  2,720,664
Total Indexing:        2 MB
Total Indexing Millis: 263

Node:1:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=784KB, Content=5022
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=549KB, Content=5022
Node:2:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=777KB, Content=4978
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=544KB, Content=4978

CACHE STORE DETAILS
-------------------
Total Queue Size:     6,708,931
Total Store Failures: 0
Total Store Failures: 0

NODE ID  QUEUE SIZE  WRITES  AVG BATCH  AVG WRITE  FAILURES  READS  AVG READ  TOTAL READ
      1   2,261,151   8,042        127      266ms         0      0       0ms        0.0s
      2   2,222,822   7,966        127      266ms         0      0       0ms        0.0s
      3   2,224,958   7,937        127      266ms         0      0       0ms        0.0s
----

[#get-cache-stores]
==== Get Cache Stores

include::../../build/_output/docs-gen/get_cache_stores.adoc[tag=text]

[source,bash]
----
$ cohctl get cache-stores -c local

Service/Cache:        DistributedCache/test
Cache Store Type:     WRITE-BEHIND
Total Queue Size:     6,708,931
Total Store Failures: 0
Total Store Failures: 0

NODE ID  QUEUE SIZE  WRITES  AVG BATCH  AVG WRITE  FAILURES  READS  AVG READ  TOTAL READ
      1   2,261,151   8,042        127      266ms         0      0       0ms        0.0s
      2   2,222,822   7,966        127      266ms         0      0       0ms        0.0s
      3   2,224,958   7,937        127      266ms         0      0       0ms        0.0s
----

NOTE: If you do not use the `-o wide` option, then you will only see service, cache name, count and size.

Display all caches for a particular service.

[source,bash]
----
$ cohctl get caches -c local -s PartitionedCache -o wide -m

Total Caches: 2, Total primary storage: 36 MB

SERVICE           CACHE        COUNT   SIZE  AVG SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES  TOTAL HITS  TOTAL MISSES  HIT PROB
PartitionedCache  customers  100,000  25 MB       262     200,000           0              0           0             0     0.00%
PartitionedCache  orders      10,000  11 MB     1,160      20,000      20,000              0      20,000             0   100.00%
----


[#set-cache]
==== Set Cache

include::../../build/_output/docs-gen/set_cache.adoc[tag=text]

See the {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html[Cache MBean Reference]
for more information on the above attributes.

*Examples*

Set the expiry delay for all nodes to 30 seconds. (we are assuming we have 3 storage-enabled nodes)

[source,bash]
----
$ cohctl set cache test -a expiryDelay -v 30 -s PartitionedCache
Using cluster connection 'local' from current context.

Selected service/cache: PartitionedCache/test
Are you sure you want to set the value of attribute expiryDelay to 30 in tier back for all 3 nodes? (y/n) y
operation completed
----

NOTE: See <<docs/examples/15_set_cache_attrs.adoc,here>> for a more detailed example of this command.


=== See Also

* <<docs/reference/20_services.adoc,Services>>
* <<docs/reference/30_topics.adoc,Topics>>


