///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2023 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Caches

== Caches

=== Overview
There are various commands that allow you to work with and manage cluster caches.

* <<get-caches, `cohctl get caches`>> - displays the caches for a cluster
* <<describe-cache, `cohctl describe cache`>> - shows information related to a specific cache and service
* <<get-cache-stores, `cohctl get cache-stores`>> - displays cache stores for a cache and service
* <<get-cache-storage, `cohctl get cache-storage`>> - displays cache storage information for a cache and service
* <<get-cache-access, `cohctl get cache-access`>> - displays cache access information for a cache and service
* <<get-cache-indexes, `cohctl get cache-indexes`>> - displays cache index information for a cache and service
* <<set-cache, `cohctl set cache`>> - sets an attribute for a cache across one or more members
* <<truncate-cache, `cohctl truncate cache`>> - truncates a caches contents, not generating any cache events
* <<clear-cache, `cohctl clear cache`>> - clears a caches contents

[#get-caches]
==== Get Caches

include::../../build/_output/docs-gen/get_caches.adoc[tag=text]

*Examples*

Display all caches and display cache size in MB using `-m` option.

[source,bash]
----
cohctl get caches -c local -o wide -m
----
Output:
[source,bash]
----
Total Caches: 2, Total primary storage: 36 MB

SERVICE           CACHE        COUNT   SIZE  AVG SIZE     PUTS    GETS  REMOVES    HITS  MISSES  HIT PROB
PartitionedCache  customers  100,000  25 MB       262  200,000       0        0       0       0     0.00%
PartitionedCache  orders      10,000  11 MB     1,160   20,000  20,000        0  20,000       0   100.00%
----

NOTE: If you do not use the `-o wide` option, then you will only see service, cache name, count and size.

Display all caches for a particular service.

[source,bash]
----
cohctl get caches -c local -s PartitionedCache -o wide -m
----
Output:
[source,bash]
----
Total Caches: 2, Total primary storage: 36 MB

SERVICE           CACHE        COUNT   SIZE  AVG SIZE     PUTS    GETS  REMOVES    HITS  MISSES  HIT PROB
PartitionedCache  customers  100,000  25 MB       262  200,000       0        0       0       0     0.00%
PartitionedCache  orders      10,000  11 MB     1,160   20,000  20,000        0  20,000       0   100.00%
----

[#describe-cache]
==== Describe Cache

include::../../build/_output/docs-gen/describe_cache.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl describe cache orders -c local -s PartitionedCache -m
----
Output:
[source,bash]
----
CACHE DETAILS
-------------
Service         :  PartitionedCache
Name            :  orders
Type            :  Cache
Description     :  Implementation: com.tangosol.net.cache.LocalCache
Cache Store Type:  NONE

CACHE SIZE AND ACCESS DETAILS
-----------------------------
NODE ID  TIER   COUNT  SIZE    PUTS    GETS  REMOVES
      1  back   5,022  5 MB   5,022  10,044        0
      2  back   4,978  5 MB   4,978   9,956        0
      3  front      0  0 MB  10,000       0        0

CACHE STORAGE DETAILS
---------------------
NODE ID  TIER   LOCKS GRANTED  LOCKS PENDING  LISTENERS  MAX QUERY MS  MAX QUERY DESC
      1  back               0              0          0             0
      2  back               0              0          0             0
      3  front              0              0          0             0

INDEX DETAILS
-------------
Total Indexing Bytes:  2,720,664
Total Indexing:        2 MB
Total Indexing Millis: 263

Node:1:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=784KB, Content=5022
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=549KB, Content=5022
Node:2:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=777KB, Content=4978
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=544KB, Content=4978

CACHE STORE DETAILS
-------------------
Total Queue Size:     6,708,931
Total Store Failures: 0
Total Store Failures: 0

NODE ID  QUEUE SIZE  WRITES  AVG BATCH  AVG WRITE  TOTAL WRITE  FAILURES  READS  AVG READ  TOTAL READ
      1   2,261,151   8,042        127      266ms      35m 43s         0      0       0ms        0.0s
      2   2,222,822   7,966        127      266ms      35m 21s         0      0       0ms        0.0s
      3   2,224,958   7,937        127      266ms      35m 18s         0      0       0ms        0.0s
----

NOTE: You may omit the service name option if the cache name is unique.

NOTE: You can also use the `-o wide` option to display more detailed information.

NOTE: The default memory display format is bytes but can be changed by using `-k`, `-m` or `-g`.

[source,bash]
----
cohctl describe cache test -c local -s PartitionedCache -o wide -m
----
Output:
[source,bash]
----
CACHE DETAILS
-------------
Service         :  PartitionedCache
Name            :  orders
Type            :  Cache
Description     :  Implementation: com.tangosol.net.cache.LocalCache
Cache Store Type:  NONE

CACHE SIZE AND ACCESS DETAILS
-----------------------------
NODE ID  TIER   COUNT  SIZE  TOTAL PUTS  TOTAL GETS  TOTAL REMOVES    HITS  MISSES  HIT PROB  STORE READS  WRITES  FAILURES
      1  back   5,022  5 MB       5,022      10,044              0  10,044       0   100.00%           -1      -1        -1
      2  back   4,978  5 MB       4,978       9,956              0   9,956       0   100.00%           -1      -1        -1
      3  front      0  0 MB      10,000           0              0       0       0     0.00%           -1      -1        -1

CACHE STORAGE DETAILS
---------------------
NODE ID  TIER   LOCKS GRANTED  LOCKS PENDING  LISTENERS  MAX QUERY MS  MAX QUERY DESC  NO OPT AVG  OPT AVG  INDEX SIZE  INDEXING MILLIS
      1  back               0              0          0             0                      0.0000   0.0000        1 MB              118
      2  back               0              0          0             0                      0.0000   0.0000        1 MB              145
      3  front              0              0          0             0                      0.0000   0.0000        0 MB                0

INDEX DETAILS
-------------
Total Indexing Bytes:  2,720,664
Total Indexing:        2 MB
Total Indexing Millis: 263

Node:1:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=784KB, Content=5022
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=549KB, Content=5022
Node:2:   SimpleMapIndex: Extractor=.toString(), Ordered=true, Footprint=777KB, Content=4978
          SimpleMapIndex: Extractor=.hashCode(), Ordered=true, Footprint=544KB, Content=4978

CACHE STORE DETAILS
-------------------
Total Queue Size:     6,708,931
Total Store Failures: 0
Total Store Failures: 0

NODE ID  QUEUE SIZE  WRITES  AVG BATCH  AVG WRITE  FAILURES  READS  AVG READ
      1   2,261,151   8,042        127      266ms         0      0       0ms
      2   2,222,822   7,966        127      266ms         0      0       0ms
      3   2,224,958   7,937        127      266ms         0      0       0ms
----

[#get-cache-stores]
==== Get Cache Stores

include::../../build/_output/docs-gen/get_cache_stores.adoc[tag=text]

[source,bash]
----
cohctl get cache-stores -c local test -s DistributedCache
----
Output:
[source,bash]
----
Service/Cache:        DistributedCache/test
Cache Store Type:     WRITE-BEHIND
Total Queue Size:     6,708,931
Total Store Failures: 0
Total Store Failures: 0

NODE ID  QUEUE SIZE  WRITES  AVG BATCH  AVG WRITE  FAILURES  READS  AVG READ
      1   2,261,151   8,042        127      266ms         0      0       0ms
      2   2,222,822   7,966        127      266ms         0      0       0ms
      3   2,224,958   7,937        127      266ms         0      0       0ms
----

You may omit the service name if the cache name is unique.

NOTE: If you do not use the `-o wide` option, then you will only see service, cache name, count and size.

[#get-cache-storage]
==== Get Cache Storage

include::../../build/_output/docs-gen/get_cache_storage.adoc[tag=text]

[source,bash]
----
cohctl get cache-storage -c local test
----
Output:
[source,bash]
----

Cache: test

NODE ID  TIER  LOCKS GRANTED  LOCKS PENDING  KEY LISTENERS  FILTER LISTENERS  MAX QUERY MS  MAX QUERY DESC
      1  back              0              0              0                 0             0
      2  back              0              0              0                 0             0
      3  back              0              0              0                 0             0
----

[#get-cache-access]
==== Get Cache Access

include::../../build/_output/docs-gen/get_cache_access.adoc[tag=text]

[source,bash]
----
cohctl get cache-access -c local test
----
Output:
[source,bash]
----
Cache: test

NODE ID  TIER  COUNT  SIZE  PUTS  GETS  REMOVES  CLEARS  EVICTIONS
      1  back      0  0 MB     0     0        0       2          0
      2  back      0  0 MB     2     0        2       2          0
      3  back      0  0 MB     0     0        0       2          0
----

[#get-cache-indexes]
==== Get Cache Indexes

include::../../build/_output/docs-gen/get_cache_indexes.adoc[tag=text]

[source,bash]
----
cohctl get cache-indexes -c local test
----
Output:
[source,bash]
----
Cache: test

Total Indexing Bytes:  49,756
Total Indexing:        0 MB
Total Indexing Millis: 1,942

Node:2:   PartitionedIndex: Extractor=.toString()(), Ordered=true, Footprint=16.2KB
Node:1:   PartitionedIndex: Extractor=.toString()(), Ordered=true, Footprint=16.2KB
Node:3:   PartitionedIndex: Extractor=.toString()(), Ordered=true, Footprint=16.0KB
----

NOTE: Depending upon the Coherence version, you may not see all the above information.


[#set-cache]
==== Set Cache

include::../../build/_output/docs-gen/set_cache.adoc[tag=text]

See the {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html[Cache MBean Reference]
for more information on the above attributes.

*Examples*

Set the expiry delay for all nodes to 30 seconds. (we are assuming we have 3 storage-enabled nodes)

[source,bash]
----
cohctl set cache test -a expiryDelay -v 30 -s PartitionedCache -c local
----
Output:
[source,bash]
----
Selected service/cache: PartitionedCache/test
Are you sure you want to set the value of attribute expiryDelay to 30 in tier back for all 3 nodes? (y/n) y
operation completed
----

NOTE: See <<docs/examples/15_set_cache_attrs.adoc,here>> for a more detailed example of this command.

[#truncate-cache]
==== Truncate Cache

include::../../build/_output/docs-gen/truncate_cache.adoc[tag=text]

[source,bash]
----
cohctl truncate cache test -c local
----
Output:
[source,bash]
----
Are you sure you want to truncate cache test in service PartitionedCache? (y/n) y
operation completed
----

NOTE: You may omit the service name option if the cache name is unique.

[#clear-cache]
==== Clear Cache

include::../../build/_output/docs-gen/clear_cache.adoc[tag=text]

[source,bash]
----
cohctl clear cache test -c local
----
Output:
[source,bash]
----
Are you sure you want to clear cache test in service PartitionedCache? (y/n) y
operation completed
----

NOTE: You may omit the service name option if the cache name is unique.

=== See Also

* <<docs/reference/20_services.adoc,Services>>
* <<docs/reference/30_topics.adoc,Topics>>


