///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2024 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Proxy Servers

== Proxy Servers

=== Overview
There are various commands that allow you to work with and manage proxy servers.

* <<get-proxies, `cohctl get proxies`>> - displays the proxy servers for a cluster
* <<get-proxy-members, `cohctl get proxy-members`>> - displays proxy members for a specific proxy server
* <<get-proxy-connections, `cohctl get proxy-connections`>> - displays proxy server connections for a specific proxy server
* <<describe-proxy, `cohctl describe proxy`>> - shows information related to a specific proxy server

[#get-proxies]
==== Get Proxies

include::../../build/_output/docs-gen/get_proxies.adoc[tag=text]

*Examples*

Display all proxy servers.

[source,bash]
----
cohctl get proxies -c local
----
Output:
[source,bash]
----
SERVICE NAME        TOTAL CONNECTIONS  TOTALDATA SENT  TOTALDATA REC
"$SYS:SystemProxy"                  0            0 MB           0 MB
Proxy                               2           13 MB           0 MB
----

NOTE: You can also use `-o wide` to display more columns.

[#get-proxy-members]
==== Get Proxy Members

include::../../build/_output/docs-gen/get_proxy_members.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl get proxy-members Proxy -c local
----
Output:
[source,bash]
----

NODE ID  HOST IP              SERVICE NAME  CONNECTIONS  DATA SENT  DATA REC  MSG SENT  MSG RCV  BYTES BACKLOG  MSG BACKLOG  UNAUTH
2        0.0.0.0:60488.38858  Proxy                   1       4 MB      0 MB        10       15              0            0       0
3        0.0.0.0:60489.34448  Proxy                   0       0 MB      0 MB         0        1              0            0       0
4        0.0.0.0:60490.43677  Proxy                   1       8 MB      0 MB        15       20              0            0       0
----

NOTE: You can also use `-o wide` to display more columns.

[#get-proxy-connections]
==== Get Proxy Connections

include::../../build/_output/docs-gen/get_proxy_connections.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl get proxy-connections Proxy -c local
----
Output:
[source,bash]
----
NODE ID    CONN MS  CONN TIME  REMOTE ADDR/PORT  BYTES SENT  BYTES REC  BACKLOG  CLIENT PROCESS  CLIENT ROLE
      1    236,916    03m 56s   127.0.0.1:58819        0 MB       0 MB        0           55414  TangosolCoherenceDslqueryQueryPlus
      1    538,395    08m 58s   127.0.0.1:58666        0 MB       0 MB        0           54769  TangosolCoherenceDslqueryQueryPlus
      2  1,177,423    19m 37s   127.0.0.1:58075        1 MB       0 MB        0           45646  TangosolCoherenceDslqueryQueryPlus
----

You can use `-o wide` to display more columns as described below.

[source,bash]
----
cohctl get proxy-connections Proxy -o wide -c local
----
Output:
[source,bash]
----
NODE ID    CONN MS  CONN TIME  REMOTE ADDR/PORT  BYTES SENT  BYTES REC  BACKLOG  CLIENT PROCESS  CLIENT ROLE                         REMOTE MEMBER
      1    275,256    04m 35s   127.0.0.1:58819        0 MB       0 MB        0           55414  TangosolCoherenceDslqueryQueryPlus  Member(Id=0, Timest...
      1    576,736    09m 36s   127.0.0.1:58666        0 MB       0 MB        0           54769  TangosolCoherenceDslqueryQueryPlus  Member(Id=0, Timest...
      2  1,215,764    20m 15s   127.0.0.1:58075        1 MB       0 MB        0           45646  TangosolCoherenceDslqueryQueryPlus  Member(Id=0, Timest...
----

[#describe-proxy]
==== Describe Proxy

include::../../build/_output/docs-gen/describe_proxy.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl describe proxy Proxy -c local
----
Output:
[source,bash]
----
PROXY SERVICE DETAILS
---------------------
Name                                :  Proxy
Type                                :  [Proxy]
...
Transport Backlogged Connection List:  [[] []]

PROXY MEMBER DETAILS
--------------------
NODE ID  HOST IP              SERVICE NAME  CONNECTIONS  BYTES SENT  BYTES REC
1        0.0.0.0:53962.47748  Proxy                   2       1,394      2,471
2        0.0.0.0:53966.60421  Proxy                   1   1,049,157        703

PROXY CONNECTIONS
-----------------
Node Id                 :  2
Remote Address          :  127.0.0.1
...
UUID                    :  0x0000018320A6A563C0A80189867534FD64D606EA44860A00C7DBDE274D31636D

Node Id                 :  1
Remote Address          :  127.0.0.1
...
UUID                    :  0x0000018320B067FDC0A80189C594C09E90166E1F48D3806BC52F4FFE8097B050

Node Id                 :  1
Remote Address          :  127.0.0.1
...
UUID                    :  0x0000018320B501A5C0A8018931AE66ADAC4A887A2E21D5A6C51F69858097B052
----

NOTE: The above output has been truncated for brevity.

=== See Also

* <<docs/reference/20_services.adoc,Services>>



