///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Executors

== Executors

=== Overview
There are various commands that allow you to work with and manage Executors.

* <<get-executors, `cohctl get executors`>> - displays the executors for a cluster
* <<describe-executor, `cohctl describe executor`>> - shows information related to a specific executor
* <<set-executor, `cohctl set executor`>> - sets an attribute for a specific executor across all nodes

[#get-executors]
==== Get Executors

include::../../build/_output/docs-gen/get_executors.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl get executors -c local

Total executors: 3
Running tasks:   0
Completed tasks: 0

NAME         MEMBER COUNT  IN PROGRESS  COMPLETED  REJECTED  DESCRIPTION
executor1               2            0          0         0  FixedThreadPool(ThreadCount=5, ThreadFactory=default)
executor2               2            0          0         0  SingleThreaded(ThreadFactory=default)
UnNamed                 2            0          0         0  None
----

[#describe-executor]
==== Describe Executor

include::../../build/_output/docs-gen/describe_executor.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl describe executor executor1 -c local

EXECUTOR DETAILS
----------------
Name                   :  executor1
Member Id              :  1
Description            :  SingleThreaded(ThreadFactory=default)
Id                     :  3af3cb00-b87d-4b89-ae9f-2107743b0741
Location               :  Member(Id=1, Timestamp=2021-12-02 15:16:21.247, Address=192.168.1.120:64409, MachineId=3603, Location=process:35013, Role=Management)
Member Count           :  0
State                  :  RUNNING
Tasks Completed Count  :  0
Tasks In Progress Count:  0
Tasks Rejected Count   :  0
Trace Logging          :  false

Name                   :  executor1
Member Id              :  2
Description            :  SingleThreaded(ThreadFactory=default)
Id                     :  cd7241ce-2a0a-41f4-85cd-538513fba2ac
Location               :  Member(Id=2, Timestamp=2021-12-02 15:28:50.824, Address=192.168.1.120:64911, MachineId=3603, Location=process:37972, Role=TangosolNetCoherence)
Member Count           :  0
State                  :  RUNNING
Tasks Completed Count  :  0
Tasks In Progress Count:  0
Tasks Rejected Count   :  0
Trace Logging          :  false
----


[#set-executor]
==== Set Executors

include::../../build/_output/docs-gen/set_executor.adoc[tag=text]

*Examples*

Turn on trace logging for the coherence-concurrent-default-executor executor.

[source,bash]
----
$ cohctl set executor coherence-concurrent-default-executor -a traceLogging -v true -c local

Are you sure you want to set the value of attribute traceLogging to true for coherence-concurrent-default-executor? (y/n) y
operation completed
----





