///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Resetting Statistics

== Resetting Statistics

=== Overview
This section contains commands for resetting MBean statistics which can be
useful when you are running performance tests.

For most commands you can reset for all members or specify a comma-separated list of members
using the `-m` option.

See {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html[MBean Reference]
for details on what MBeans support the `resetStatistics` operation.

NOTE: Only the most recent Coherence versions support all the commands below and you be shown
a message if the operation is no supported for your specific Coherence version.

* <<reset-cache-stats, `cohctl reset cache-stats`>> - resets cache statistics for all cache members or specific cache members
* <<reset-executor-stats, `cohctl reset executor-stats`>> - resets statistics for an executor
* <<reset-federation-stats, `cohctl reset federation-stats`>> - resets federation statistics for all federation or specific federation members
* <<reset-flashjournal-stats, `cohctl reset flashjournal-stats`>> - resets statistics for all flash journals
* <<reset-ramjournal-stats, `cohctl reset ramjournal-stats`>> - resets statistics for all ram journals
* <<reset-ramjournal-stats, `cohctl reset ramjournal-stats`>> - resets statistics for all ram journals
* <<reset-member-stats, `cohctl reset member-stats`>> - resets statistics for all or a specific member
* <<reset-reporter-stats, `cohctl reset reporter-stats`>> - resets reporter statistics for all or a specific reporter
* <<reset-service-stats, `cohctl reset service-stats`>> - resets services statistics for all service members or specific service members

[#reset-cache-stats]
==== Reset Cache Statistics

include::../../build/_output/docs-gen/reset_cache_stats.adoc[tag=text]

*Examples*

Reset statistics for all cache members for cache `test`.

[source,bash]
----
$ cohctl get caches -c local

Total Caches: 1, Total primary storage: 30 MB

SERVICE           CACHE    COUNT   SIZE
PartitionedCache  test   123,000  30 MB

$ cohctl reset cache-stats test -s PartitionedCache
Using cluster connection 'local' from current context.

Are you sure you want to reset cache statistics for cache test, service PartitionedCache for all 3 nodes? (y/n) y
operation completed
----

Reset statistics for cache members 1 and 2 for cache `test`.

[source,bash]
----
$ cohctl reset cache-stats test -s PartitionedCache -n 1,2 -c local

Are you sure you want to reset cache statistics for cache test, service PartitionedCache for 2 node(s)? (y/n) y
operation completed
----

[#reset-executor-stats]
==== Reset Executor Statistics

include::../../build/_output/docs-gen/reset_executor_stats.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl get executors -c local

Total executors: 1
Running tasks:   0
Completed tasks: 0

NAME                                   MEMBER COUNT  IN PROGRESS  COMPLETED  REJECTED  DESCRIPTION
coherence-concurrent-default-executor             3            0          0         0  SingleThreaded(ThreadFactory=default)
coherence-cli$ (rc)$ cohctl reset executor-stats coherence-concurrent-default-executor
Using cluster connection 'local' from current context.

Are you sure you want to reset executor statistics for exeutor coherence-concurrent-default-executor? (y/n) y
operation completed
----

[#reset-federation-stats]
==== Reset Federation Statistics

include::../../build/_output/docs-gen/reset_federation_stats.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl get federation all -c local

SERVICE           DESTINATION  MEMBERS  STATES  DATA SENT  MSG SENT  REC SENT  CURR AVG BWIDTH
FederatedService  cluster2           1  [IDLE]       3 MB    13,873    30,000          0.0Mbps

$ cohctl reset federation-stats FederatedService -p cluster2 -T outgoing -c local

Are you sure you want to reset federation statistics for service FederatedService, participant cluster2, type outgoing for all 1 nodes? (y/n) y
operation completed
----

[#reset-ramjournal-stats]
==== Reset RAM Journal Statistics

include::../../build/_output/docs-gen/reset_ramjournal_stats.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl reset ramjournal-stats -c local

Are you sure you want to reset ramjournal statistics for all 2 nodes? (y/n) y
operation completed
----

[#reset-flashjournal-stats]
==== Reset Flash Journal Statistics

include::../../build/_output/docs-gen/reset_flashjournal_stats.adoc[tag=text]

*Examples*

[source,bash]
----
$ cohctl reset flashjournal-stats -c local

Are you sure you want to reset flashjournal statistics for all 2 nodes? (y/n) y
operation completed
----

[#reset-member-stats]
==== Reset Member Statistics

include::../../build/_output/docs-gen/reset_member_stats.adoc[tag=text]

*Examples*

Reset member statistics for member 1 and 3.

[source,bash]
----
$ cohctl get members -c local

Total cluster members: 3
Cluster Heap - Total: 384 MB Used: 127 MB Available: 257 MB (66.9%)
Storage Heap - Total: 384 MB Used: 127 MB Available: 257 MB (66.9%)

NODE ID  ADDRESS     PORT   PROCESS  MEMBER     ROLE             STORAGE  MAX HEAP  USED HEAP  AVAIL HEAP
      1  /127.0.0.1  58938    96295  storage-0  CoherenceServer  true       128 MB      65 MB       63 MB
      2  /127.0.0.1  58944    96303  storage-2  CoherenceServer  true       128 MB      41 MB       87 MB
      3  /127.0.0.1  58941    96296  storage-1  CoherenceServer  true       128 MB      21 MB      107 MB
$ cohctl reset member-stats -n 1,3 -c local

Are you sure you want to reset members statistics for 2 node(s)? (y/n) y
operation completed
----

[#reset-reporter-stats]
==== Reset Reporter Statistics

include::../../build/_output/docs-gen/reset_reporter_stats.adoc[tag=text]

[source,bash]
----
$ cohctl get reporters -c local

NODE ID  STATE    CONFIG FILE               OUTPUT PATH                               BATCH#  LAST REPORT  LAST RUN   AVG RUN  INTERVAL  AUTOSTART
      1  Stopped  reports/report-group.xml  /Users/timmiddleton/Documents/Coheren...       0                    0ms  0.0000ms        60  false
      2  Stopped  reports/report-group.xml  /Users/timmiddleton/Documents/Coheren...       0                    0ms  0.0000ms        60  false
      3  Stopped  reports/report-group.xml  /Users/timmiddleton/Documents/Coheren...       0                    0ms  0.0000ms        60  false
$ cohctl reset reporter-stats -c local

Are you sure you want to reset reporters statistics for all 3 nodes? (y/n) y
operation completed
----

[#reset-service-stats]
==== Reset Service Statistics

include::../../build/_output/docs-gen/reset_service_stats.adoc[tag=text]

[source,bash]
----
$ cohctl get services -c  local

SERVICE NAME            TYPE              MEMBERS  STATUS HA  STORAGE  PARTITIONS
Proxy                   Proxy                   3  n/a             -1          -1
PartitionedTopic        PagedTopic              3  NODE-SAFE        3         257
PartitionedCache        DistributedCache        3  NODE-SAFE        3         257
ManagementHttpProxy     Proxy                   1  n/a             -1          -1
"$SYS:HealthHttpProxy"  Proxy                   3  n/a             -1          -1
"$SYS:Config"           DistributedCache        3  NODE-SAFE        3         257
"$SYS:ConcurrentProxy"  Proxy                   3  n/a             -1          -1
"$SYS:Concurrent"       DistributedCache        3  NODE-SAFE        3         257

$ cohctl reset service-stats PartitionedCache -c local

Are you sure you want to reset service statistics for all 3 nodes? (y/n) y
operation completed
----