///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2023 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Creating Clusters

== Creating Clusters

=== Overview
There are various cluster commands that allow you to create and work with local development based clusters.

These commands allow you to create local only development based clusters (scoped to localhost) for Coherence CE 22.06.x and
Commercial 14.1.1.2206.x versions and above. You must have the following setup for this to work:

1. Java 17+ executable on the PATH, if you are using the default Coherence CE {coherence-version} version.
2. Maven 3.6+ or JDK compatible Gradle version 7.+ executable on the PATH.

NOTE: If you wish to use an earlier version of Coherence such as CE 22.06, you can use JDK11+.

NOTE: Maven is used by default for dependency resolution and classpath generation, but if you prefer Gradle, then use the
following: `cohctl set use-grade true`. You can revert to Maven by using `cohctl set use-gradle false`.

Once you create a local cluster, you can manage and monitor these clusters in the same way as you can with discovered
or manually added clusters. You can also run the Coherence console and CohQL (Query client) against these clusters.

When you create a cluster, the first node started will always have management over REST enabled.

You may also specify a profile when you start a cluster using the `-P` option. The value of the profile
, which is a string containing `-Dkey=value` pairs, will be included in the cache servers started.

On first creation of a Coherence cluster, if your Maven or Gradle repository is empty, it may take a short while to download the minimal depdencies.

NOTE: These commands are experimental only and may be changed or removed in the future. It is *not supported* to use
these commands to create production clusters.

*Creating and controlling clusters*

* <<create-cluster, `cohctl create cluster`>> - creates a local cluster and adds to the cohctl.yaml file
* <<scale-cluster, `cohctl scale cluster`>> - scales a cluster that was manually created
* <<stop-cluster, `cohctl stop cluster`>> - stops a cluster that was manually created or started
* <<start-cluster, `cohctl start cluster`>> - starts a cluster that was manually created
* <<start-console, `cohctl start console`>> - starts a console client against a cluster that was manually created
* <<start-cohql, `cohctl start cohql`>> - starts a CohQL client against a cluster that was manually created
* <<start-class, `cohctl start class`>> - starts a specific Java class against a cluster that was manually created

*Setting dependency tool*

* <<set-use-gradle, `cohctl set use-gradle`>> - sets whether to use gradle for dependency management
* <<get-use-gradle, `cohctl get use-gradle`>> - displays the current setting for using gradle for dependency management

*Setting default heap sizes*

* <<set-default-heap, `cohctl set default-heap`>> - sets default heap for creating and starting clusters
* <<get-default-heap, `cohctl get default-heap`>> - gets default heap for creating and starting clusters
* <<clear-default-heap, `cohctl clear default-heap`>> - clears default heap for creating and starting clusters

*Creating and managing profiles*

* <<set-profile, `cohctl set profile`>> - set a profile value for creating and starting clusters
* <<remove-profile, `cohctl remove profile`>> - removes a profile value from the list of profile
* <<get-profiles, `cohctl get profiles`>> - displays the profiles that have been created

[#create-cluster]
==== Create Cluster

include::../../build/_output/docs-gen/create_cluster.adoc[tag=text]

NOTE: The log files are stored under the `.cohctl/logs/` directory off your home directory. You can
change this for an individual cluster by specifying the `-L` option when you create the cluster.

*Examples*

Add and start a cluster using all default values.

NOTE: After the cluster has been created, the current context is automatically set to the new cluster.

[source,bash,subs="attributes"]
----
cohctl create cluster local
----
Output:
[source,bash,subs="attributes"]
----
Cluster name:           local
Cluster version:        {coherence-version}
Cluster port:           7574
Partition count:        257
Management port:        30000
Server count:           3
Initial memory:         128m
Persistence mode:       on-demand
Group ID:               com.oracle.coherence.ce
Additional artifacts:
Log destination root:
Dependency tool:        mvn
Are you sure you want to create the cluster with the above details? (y/n) y

Checking 3 Maven dependencies...
- com.oracle.coherence.ce:coherence:{coherence-version}
- com.oracle.coherence.ce:coherence-json:{coherence-version}
- org.jline:jline:3.20.0
Starting 3 cluster members for cluster local
Starting cluster member storage-0...
Starting cluster member storage-1...
Starting cluster member storage-2...
Cluster added and started
Current context is now local
----
Display the cluster members

[source,bash]
----
cohctl get members
----
Output:
[source,bash]
----
Using cluster connection 'local' from current context.

Total cluster members: 3
Cluster Heap - Total: 384 MB Used: 123 MB Available: 261 MB (68.0%)
Storage Heap - Total: 384 MB Used: 123 MB Available: 261 MB (68.0%)

NODE ID  ADDRESS     PORT   PROCESS  MEMBER     ROLE             STORAGE  MAX HEAP  USED HEAP  AVAIL HEAP
      1  /127.0.0.1  61565    63754  storage-1  CoherenceServer  true       128 MB      28 MB      100 MB
      2  /127.0.0.1  61566    63753  storage-0  CoherenceServer  true       128 MB      25 MB      103 MB
      3  /127.0.0.1  61567    63755  storage-2  CoherenceServer  true       128 MB      70 MB       58 MB
----

NOTE: By default, Coherence CE groupId is used and the version is {coherence-version}. You can change this via using `-C` for commercial and `-v` to change the Coherence version.

NOTE: Additional dependencies `coherence-json` is included to enable Management over REST and `jline` is included for `CohQL` history support.

Add and start a commercial Coherence cluster (14.1.1.2206.5) and set initial memory for each cluster to 1g and use active persistence mode.

[source,bash]
----
cohctl create cluster local -C -v 14.1.1-2206-5 -M 1g -P active -S
----
Output:
[source,bash]
----
Cluster name:         local
Cluster version:      14.1.1-2206-5
Cluster port:         7574
Partition count:      257
Management port:      30000
Server count:         3
Initial memory:       1g
Persistence mode:     active
Group ID:             com.oracle.coherence
Additional artifacts:
Log destination root:
Dependency tool:      mvn
Are you sure you want to create the cluster with the above details? (y/n) y

Skipping downloading Maven artifcts
Starting 3 cluster members for cluster local
Starting cluster member storage-0...
Starting cluster member storage-1...
Starting cluster member storage-2...
Cluster added and started
----

NOTE: In this example we are using the `-S` option to skip downloading maven artifacts as we know they are already installed locally.

Add and start a cluster using all default values but include additional `coherence-rest` and opentracing dependencies.

[source,bash]
----
cohctl create cluster local -a coherence-rest,io.opentracing:opentracing-api:0.33.0,io.opentracing:opentracing-util:0.33.0
----

Output:
[source,bash,subs="attributes"]
----
Cluster name:           local
Cluster version:        {coherence-version}
Cluster port:           7574
Partition count:        257
Management port:        30000
Server count:           3
Initial memory:         128m
Persistence mode:       on-demand
Group ID:               com.oracle.coherence.ce
Additional artifacts:   coherence-rest,io.opentracing:opentracing-api:0.33.0,io.opentracing:opentracing-util:0.33.0
Log destination root:
Dependency tool:        mvn
Are you sure you want to create the cluster with the above details? (y/n) y

Checking 6 Maven dependencies...
- com.oracle.coherence.ce:coherence:{coherence-version}
- com.oracle.coherence.ce:coherence-json:{coherence-version}
- com.oracle.coherence.ce:coherence-rest:{coherence-version}
- io.opentracing:opentracing-api:0.33.0
- io.opentracing:opentracing-util:0.33.0
- org.jline:jline:3.20.0
Starting 3 cluster members for cluster local
Starting cluster member storage-0...
Starting cluster member storage-1...
Starting cluster member storage-2...
Cluster added and started with process ids: [3324 3330 3331]
----

[#scale-cluster]
==== Scale Cluster

include::../../build/_output/docs-gen/scale_cluster.adoc[tag=text]

[source,bash]
----
cohctl scale cluster local -r 4
----
Output:
[source,bash]
----
Are you sure you want to scale the cluster local up by 1 member(s) to 4 members? (y/n) y
Starting cluster member storage-3...
Cluster local scaled
----

NOTE: It is not yet supported to scale down a cluster.

[#stop-cluster]
==== Stop Cluster

include::../../build/_output/docs-gen/stop_cluster.adoc[tag=text]

[source,bash]
----
cohctl stop cluster local
----
Output:
[source,bash]
----
Are you sure you want to stop 3 members for the cluster local? (y/n) y
killed process 47760
killed process 47761
killed process 47762
3 processes were stopped for cluster local
----

[#start-cluster]
==== Start Cluster

include::../../build/_output/docs-gen/start_cluster.adoc[tag=text]

*Examples*

Start a cluster and specify heap size of `1g`. (default is 128m)

[source,bash]
----
cohctl start cluster local -M 1g
----
Output:
[source,bash]
----
Are you sure you want to start 3 members for cluster local? (y/n) y
Starting cluster member storage-0...
Starting cluster member storage-1...
Starting cluster member storage-2...
Cluster local and started
----

Start a cluster and specify heap size of `1g` with 4 replicas/members.

[source,bash]
----
cohctl start cluster local -M 1g -r 4
----
Output:
[source,bash]
----
Are you sure you want to start 4 members for cluster local? (y/n) y
Starting cluster member storage-0...
Starting cluster member storage-1...
Starting cluster member storage-2...
Starting cluster member storage-3...
Cluster local and started
----

[#start-console]
==== Start Console

include::../../build/_output/docs-gen/start_console.adoc[tag=text]

Start a Coherence console.

[source,bash,subs="attributes"]
----
cohctl start console -c local
----
Output:
[source,bash,subs="attributes"]
----
Starting client com.tangosol.net.CacheFactory...
2022-08-29 16:00:01.346/0.620 Oracle Coherence {coherence-version} <Info> (thread=main, member=n/a): Loaded operational configuration from "jar:file:/Users/user/.m2/repository/com/oracle/coherence/ce/coherence/{coherence-version}/coherence-{coherence-version}.jar!/tangosol-coherence.xml"
...

Map (?):
----

NOTE: Use `bye` to quit the console.

[#start-cohql]
==== Start CohQL

include::../../build/_output/docs-gen/start_cohql.adoc[tag=text]

Start a CohQL session.

[source,bash]
----
cohctl start cohql -c local
----
Output:
[source,bash]
----
Starting client com.tangosol.coherence.dslquery.QueryPlus...
Coherence Command Line Tool

CohQL>
----

NOTE: Use `bye` to quit the console.

Start a CohQL Session and execute a statement

[source,bash]
----
cohctl start cohql -c local -S "insert into test key(1) value(1)"
----

Start a CohQL Session and execute statements from a file.

[source,bash]
----
cohctl start cohql -c local -f /tmp/run.cohql
----

[#start-class]
==== Start Class

include::../../build/_output/docs-gen/start_class.adoc[tag=text]

[source,bash]
----
cohctl start class com.my.company.Class -c local
----
Output:
[source,bash]
----
Starting client com.my.company.Class...
----

[#set-use-gradle]
==== Set Use Gradle

include::../../build/_output/docs-gen/set_use_gradle.adoc[tag=text]

[source,bash]
----
cohctl set use-gradle true
----
Output:
[source,bash]
----
Use Gradle is now set to true
----

[#get-use-gradle]
==== Get Use Gradle

include::../../build/_output/docs-gen/get_use_gradle.adoc[tag=text]

[source,bash]
----
cohctl get use-gradle
----
Output:
[source,bash]
----
Use Gradle: true
----


[#set-default-heap]
==== Set Default Heap

include::../../build/_output/docs-gen/set_default_heap.adoc[tag=text]

Set default heap to 512m.

[source,bash]
----
cohctl set default-heap 512m
----
Output:
[source,bash]
----
Default heap is now set to 512m
----

[#get-default-heap]
==== Get Default Heap

include::../../build/_output/docs-gen/get_default_heap.adoc[tag=text]

[source,bash]
----
cohctl get default-heap
----
Output:
[source,bash]
----
Current default heap: 512m
----

[#clear-default-heap]
==== Clear Default Heap

include::../../build/_output/docs-gen/clear_default_heap.adoc[tag=text]

[source,bash]
----
cohctl clear default-heap
----
Output:
[source,bash]
----
Default heap has been cleared
----

NOTE: If no default-heap is set, then the default of 128m is used unless a value for `-M` is specified.

[#set-profile]
==== Set Profile

include::../../build/_output/docs-gen/set_profile.adoc[tag=text]

[source,bash]
----
cohctl set profile debug-enabled -v "-Dmy.debug.enabled=true -Dmy.debug.level=10"
----
Output:
[source,bash]
----
Are you sure you want to set the profile debug-enabled to a value of [-Dmy.debug.enabled=true -Dmy.debug.level=10]? (y/n) y
profile debug-enabled was set to value [-Dmy.debug.enabled=true -Dmy.debug.level=10]
----

When you have set the profile you can startup or create a cluster using that profile by
specifying `-P profile-name` for the `cohctl start cluster` or `cohctl create cluster` commands.

[#remove-profile]
==== Remove Profile

include::../../build/_output/docs-gen/remove_profile.adoc[tag=text]

[source,bash]
----
cohctl remove profile debug-enabled
----
Output:
[source,bash]
----
Are you sure you want to remove the profile debug-enabled? (y/n) y
profile debug-enabled was removed
----

[#get-profiles]
==== Get Profiles

include::../../build/_output/docs-gen/get_profiles.adoc[tag=text]

[source,bash]
----
cohctl get profiles
----
Output:
[source,bash]
----
PROFILE    VALUE
profile1   -Dproperty1.value=2
profile2   -Dproperty2.value=2 -Dproperty3.value=4
----

=== See Also

* <<docs/reference/05_clusters.adoc,Clusters>>




