///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2025 Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.

///////////////////////////////////////////////////////////////////////////////

= Persistence

== Persistence

=== Overview
There are various commands that allow you to work with and issue Persistence commands.

* <<get-persistence, `cohctl get persistence`>> - displays persistence information for a cluster
* <<get-snapshots, `cohctl get snapshots`>> - shows persistence snapshots for a cluster
* <<create-snapshot, `cohctl create snapshot`>> - create a snapshot for a service
* <<recover-snapshot, `cohctl recover snapshot`>> - recover a snapshot for a service
* <<remove-snapshot, `cohctl remove snapshot`>> - remove a snapshot for a service
* <<archive-snapshot, `cohctl archive snapshot`>> - archive a snapshot for a service
* <<retrieve-snapshot, `cohctl retrieve snapshot`>> - retrieve an archived snapshot for a service
* <<suspend-service, `cohctl suspend service`>> - suspends a specific service in all the members of a cluster
* <<resume-service, `cohctl resume service`>> - resumes a specific service in all the members of a cluster
* <<force-recovery, `cohctl force recovery`>> -proceeds with persistence recovery despite the dynamic quorum policy objections

See the {commercial-docs-base-url}/administer/persisting-caches.html[Coherence Documentation] for
more information on Persistence.

[#get-persistence]
==== Get Persistence

include::../../build/_output/docs-gen/get_persistence.adoc[tag=text]

*Examples*

Display all persistence services.

[source,bash]
----
cohctl get persistence -c local
----
Output:
[source,bash]
----
Total Active Space Used: 7MB

SERVICE NAME       STORAGE COUNT  PERSISTENCE MODE  ACTIVE SPACE USED  AVG LATENCY  MAX LATENCY  SNAPSHOTS  STATUS
PartitionedTopic               4  active                      652,342      0.000ms          0ms          0  Idle
PartitionedCache2              4  active                      365,946      0.000ms          0ms          0  Idle
PartitionedCache               4  active                    6,331,471      0.242ms        188ms          2  Idle
----

[#get-snapshots]
==== Get Snapshots

include::../../build/_output/docs-gen/get_snapshots.adoc[tag=text]

*Examples*

Display snapshots for all services.

[source,bash]
----
cohctl get snapshots -c local
----
Output:
[source,bash]
----
SERVICE            SNAPSHOT NAME
PartitionedCache2  snapshot-test
PartitionedCache   snapshot-1
PartitionedCache   snapshot-2
----

Display snapshots for a specific service.

[source,bash]
----
cohctl get snapshots -c local -s PartitionedCache
----
Output:
[source,bash]
----
SERVICE            SNAPSHOT NAME
PartitionedCache   snapshot-1
PartitionedCache   snapshot-2
----

Display *archived* snapshots for all services.

[source,bash]
----
cohctl get snapshots -c local -a
----
Output:
[source,bash]
----
SERVICE            ARCHIVED SNAPSHOT NAME
PartitionedCache2  snapshot-test
PartitionedCache   snapshot-1
----

Display *archived* snapshots for a specific service.

[source,bash]
----
cohctl get snapshots -c local -s PartitionedCache -a
----
Output:
[source,bash]
----
SERVICE           ARCHIVED SNAPSHOT NAME
PartitionedCache  snapshot-1
----

[#create-snapshot]
==== Create Snapshot

include::../../build/_output/docs-gen/create_snapshot.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl create snapshot my-snapshot -s PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform create snapshot for snapshot my-snapshot and service PartitionedCache? (y/n) y

Operation create snapshot for snapshot my-snapshot on service PartitionedCache invoked
Please use 'cohctl get persistence' to check for idle status to ensure the operation completed
----

NOTE: This and other commands that create, remove, archive, retrieve or recover snapshots submit this request to
the service to perform the operation only. The return of the command prompt does not mean the operation has been
completed on the service.
You should use `cohctl get persistence` to ensure the status is Idle and check Coherence log files before continuing.

[#recover-snapshot]
==== Recover Snapshot

include::../../build/_output/docs-gen/recover_snapshot.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl recover snapshot my-snapshot -s PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform recover snapshot for snapshot my-snapshot and service PartitionedCache? (y/n) y

Operation recover snapshot for snapshot my-snapshot on service PartitionedCache invoked
Please use 'cohctl get persistence' to check for idle status to ensure the operation completed
----

NOTE: This is a destructive command and will remove all current caches for the specified service and
replace them with the contents of the caches in the snapshot.

[#remove-snapshot]
==== Remove Snapshot

include::../../build/_output/docs-gen/remove_snapshot.adoc[tag=text]

*Examples*

Remove a local snapshot.

[source,bash]
----
cohctl recover snapshot my-snapshot -s PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform remove snapshot for snapshot my-snapshot and service PartitionedCache? (y/n) y

Operation remove snapshot for snapshot my-snapshot on service PartitionedCache invoked
Please use 'cohctl get persistence' to check for idle status to ensure the operation completed
----

Remove an *archived* snapshot.

[source,bash]
----
cohctl recover snapshot my-snapshot -s PartitionedCache -a -c local
----
Output:
[source,bash]
----
Are you sure you want to perform remove archived snapshot for snapshot my-snapshot and service PartitionedCache? (y/n) y

Operation remove archived snapshot for snapshot my-snapshot on service PartitionedCache invoked
Please use 'cohctl get persistence' to check for idle status to ensure the operation completed
----

[#archive-snapshot]
==== Archive Snapshot

include::../../build/_output/docs-gen/archive_snapshot.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl archive snapshot my-snapshot -s PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform archive snapshot for snapshot my-snapshot and service PartitionedCache? (y/n) y

Operation archive snapshot for snapshot my-snapshot on service PartitionedCache invoked
Please use 'cohctl get persistence' to check for idle status to ensure the operation completed
----

NOTE: When you issue the archive snapshot command, the snapshots on the separate servers are sent to a
central location. Coherence provides a directory archiver implementation which will store the archive on a shared
filesystem available to all members.  You can also create your own archiver implementations.
See {commercial-docs-base-url}/administer/persisting-caches.html[the Coherence documentation]
for more details.

[#retrieve-snapshot]
==== Retrieve Snapshot

include::../../build/_output/docs-gen/retrieve_snapshot.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl retrieve snapshot my-snapshot -s PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform retrieve snapshot for snapshot my-snapshot and service PartitionedCache? (y/n) y

Operation retrieve snapshot for snapshot my-snapshot on service PartitionedCache invoked
Please use 'cohctl get persistence' to check for idle status to ensure the operation completed
----

NOTE: This operation will retrieve and archived snapshot and distribute it across all available members. Once it has
been retrieved it can be recovered. You must ensure that a snapshot with the same name as the archived snapshot does
not exist before you retrieve it.

[#suspend-service]
==== Suspend Service

include::../../build/_output/docs-gen/suspend_service.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl suspend service PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform suspend service for service PartitionedCache? (y/n) y
operation completed
----

NOTE: You can use the command `cohctl get services -o wide` to show if services have been suspended.

[#resume-service]
==== Resume Service

include::../../build/_output/docs-gen/resume_service.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl resume service PartitionedCache -c local
----
Output:
[source,bash]
----
Are you sure you want to perform resume service for service PartitionedCache? (y/n) y
operation completed
----

[#force-recovery]
==== Force Recovery

include::../../build/_output/docs-gen/force_recovery.adoc[tag=text]

*Examples*

[source,bash]
----
cohctl force recovery PartitionedCache -c local
----
Output:
[source,bash]
----
Warning: This may lead to the partial or full data loss of the corresponding cache service.
Are you sure you want to perform force recovery for service PartitionedCache? (y/n) y
operation force recovery on service PartitionedCache invoked
----

=== See Also

* {commercial-docs-base-url}/administer/persisting-caches.html[Persisting Caches in the Coherence Documentation]
* xref:services.adoc[Services]



