# Copyright 2021, 2024 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CLI GitHub Actions CI build - Test Monitor Cluster JDK21
# ---------------------------------------------------------------------------
name: CI Test Monitor Cluster JDK21

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        coherenceVersion:
          - 22.06.8
          - 24.03
        javaVersion:
          - 21

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.javaVersion }}
        distribution: 'zulu'

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build cohctl
      shell: bash
      run: make cohctl

    - name: Test Monitor Cluster
      shell: bash
      run: |
        sudo apt-add-repository universe -y
        sudo apt-get install expect -y
        COHERENCE_VERSION=${{ matrix.coherenceVersion }} make test-monitor-cluster

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.coherenceVersion }}-${{ matrix.javaVersion }}
        path: build/_output/test-logs
