# Copyright 2023, 2024 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CLI Compatability Tests against mainline of CLI - 14.1.1.0
# ---------------------------------------------------------------------------
name: Compatability Tests 14.1.1.0

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        coherenceVersion:
          - 14.1.1-0-19
          - 14.1.1-0-20-SNAPSHOT
        javaImage:
          - gcr.io/distroless/java:11

#   Checkout the source, we need a depth of zero to fetch all the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Docker Images
      shell: bash
      run: |
        docker pull gcr.io/distroless/java:11

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Compatability Tests
      shell: bash
      run: |
        export COHERENCE_BASE_IMAGE=${{ matrix.javaImage }}
        export COHERENCE_VERSION=${{ matrix.coherenceVersion }}
        make clean build-test-images test-e2e-standalone
        make test-clean test-discovery

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.coherenceVersion }}-${{ matrix.javaImage }}
        path: build/_output/test-logs
