# Copyright 2022, 2024 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CLI Compatability Tests against latest stable CLI version
# ---------------------------------------------------------------------------
name: Compatability Tests Released

on:
  workflow_dispatch:
  schedule:
    # Every day at 1 am
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        coherenceVersion:
          - 23.09.1
          - 23.09.2
          - 22.06.7
          - 22.06.8-SNAPSHOT
        javaImage:
          - gcr.io/distroless/java17

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Docker Images
      shell: bash
      run: |
        docker pull gcr.io/distroless/java17

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Compatability Tests
      shell: bash
      run: |
        # Getting latest version
        LATEST=$(curl -s https://oracle.github.io/coherence-cli/stable.txt)
        echo "Checkout out $LATEST"
        git checkout $LATEST
        export COHERENCE_BASE_IMAGE=${{ matrix.javaImage }}
        export COHERENCE_VERSION=${{ matrix.coherenceVersion }}
        GOBIN=`pwd`/build/tools/bin go install gotest.tools/gotestsum@v1.8.1
        make clean build-test-images test-e2e-standalone
        make test-clean test-discovery

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-output
        path: build/_output/test-logs
