# Copyright 2023 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CLI GitHub Actions CI build - Install Linux ARM
# ---------------------------------------------------------------------------
name: CI - Install ARM

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Twice a day
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Test Installing CLI via curl for Linux ARM
      shell: bash
      run: |
        docker run -it arm64v8/fedora:38 bash -c "curl -sLo /tmp/install.sh https://raw.githubusercontent.com/oracle/coherence-cli/main/install.sh && chmod u+x /tmp/install.sh && /tmp/install.sh && cohctl version"
